### ISSUE TITLE
cargo-audit fails to compile

### ISSUE THREAD

**Issue by hds** [rustsec/rustsec#1000]
Due to a breaking change in the `gix` API which `rustsec` uses via `tame-index`, `cargo-audit` is failing to build.

```sh
cargo install cargo-audit
```

Error:
```
error[E0433]: failed to resolve: could not find `state` in `worktree`
   --> /home/stainsby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustsec-0.28.1/src/repository/git/commit.rs:150:35
    |
150 |         let opts = gix::worktree::state::checkout::Options {
    |                                   ^^^^^ could not find `state` in `worktree`

error[E0433]: failed to resolve: could not find `state` in `worktree`
   --> /home/stainsby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustsec-0.28.1/src/repository/git/commit.rs:156:24
    |
156 |         gix::worktree::state::checkout(
    |                        ^^^^^ could not find `state` in `worktree`

error[E0599]: no method named `fetch_then_checkout` found for struct `tame_index::external::gix::clone::PrepareFetch` in the current scope
   --> /home/stainsby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustsec-0.28.1/src/repository/git/repository.rs:169:22
    |
162 |                   let (mut prep_checkout, out) = gix::prepare_clone(url, path)
    |  ________________________________________________-
163 | |                     .map_err(|err| {
164 | |                         format_err!(ErrorKind::Repo, "failed to prepare clone: {}", err)
165 | |                     })?
...   |
168 | |                     .configure_remote(|remote| Ok(remote.with_refspecs([REF_SPEC], DIR)?))
169 | |                     .fetch_then_checkout(&mut progress, should_interrupt)
    | |                     -^^^^^^^^^^^^^^^^^^^ method not found in `PrepareFetch`
    | |_____________________|
    | 
```

The story so far:
* There was a breaking change in `gix` going from 0.52 to 0.53 (0-major update, so this is fine)
* `tame-index` updated from `gix` 0.52` to `0.53`. This was done in a patch release (0.5.5 to 0.5.6), so it's probably considered not okay (https://github.com/EmbarkStudios/tame-index/issues/28)
* `rustsec` specifies as a dependency `tame-index` 0.5.5, but at build time is getting 0.5.6.

I don't know if there could a lock file for `cargo-audit`, I see that the checked `Cargo.lock` specifies `tame-index` 0.5.5.

**Comment by simon-an** [comment]
+1 for Cargo.lock

**Comment by pr2502** [comment]
There is a lockfile but `cargo install` ignores it by default, install with `cargo install cargo-audit --locked` to use the lockfile.

**Comment by hds** [comment]
> There is a lockfile but `cargo install` ignores it by default, install with `cargo install cargo-audit --locked` to use the lockfile.

Thanks for the hint!

**Comment by hds** [comment]
Update: `tame-index` 0.5.6 has been yanked, and it looks like compilation is already working again.
