### ISSUE TITLE
Custom cargo audit RustSec advisory database URL

### ISSUE THREAD

**Issue by MarkRx** [rustsec/rustsec#1010]
It looks like database URL is [hard coded](https://github.com/rustsec/rustsec/blob/main/rustsec/src/database.rs#L108) to https://github.com/RustSec/advisory-db.git. I cannot find a way to override it.

This should be customizable for users that run builds a corporates proxy that prevents internet access and instead need to use an internal mirror.

**Comment by tarcieri** [comment]
See also the `--url` command line argument for `cargo-audit`
