### ISSUE TITLE
cargo audit command does not provide a description

### ISSUE THREAD

**Issue by sdavids** [rustsec/rustsec#1013]
## Current

```shell
$ cargo --list
Installed Commands:
    add                  Add dependencies to a Cargo.toml manifest file
    audit
    b                    alias: build
    bench                Execute all benchmarks of a local package
```

## Expected

```shell
$ cargo --list
Installed Commands:
    add                  Add dependencies to a Cargo.toml manifest file
    audit                A USEFUL DESCRIPTION
    b                    alias: build
    bench                Execute all benchmarks of a local package
```

**Comment by tarcieri** [comment]
Are you aware of a way to actually implement this?

We don't control `cargo`

**Comment by Shnatsel** [comment]
This is in fact not currently possible, see https://github.com/rust-lang/cargo/issues/10662

**Comment by sdavids** [comment]
Should this issue not remain in some non-`closed` state so it will get picked up once https://github.com/rust-lang/cargo/issues/10662 is closed?

**Comment by tarcieri** [comment]
There's nothing actionable here until https://github.com/rust-lang/cargo/issues/10662 hypothetically lands.

We can reopen this issue if there is an upstream change.
