### ISSUE TITLE
Cyclic dependency graph error for dev-dependency

### ISSUE THREAD

**Issue by silwol** [rustsec/rustsec#1043]
Having two projects (for example `a` and `b`) in the dependency tree can trigger this error when running `cargo audit bin <binary>`:

```
error: parse error: Failed to deserialize audit data from JSON: The input JSON specifies a cyclic dependency graph
```

Precondition for this is:

- Binary project (directly or transitively) depends on project `a`
- Project `a` has a dependency on project `b`
- Project `b` has a dev-dependency on project `a`

From my experience that is a rather common setup that I've encountered in different projects.

Surprisingly this issue does not trigger when the binary project depends on project `b`.

Not sure whether the culprit here is `cargo-audit` or `cargo-auditable`, please let me know if it's actually `cargo-auditable` causing the issue.

I created a minimal example [here](https://gitlab.com/silwol/cargo-audit-dep-cycle) to quickly verify the issue.

**Comment by Shnatsel** [comment]
Thank you for the report! The issue could be in either encoding the data or in the topological sort algorithm, I'll need to take a closer look to know which one it is.

**Comment by Shnatsel** [comment]
I've confirmed that this is a bug in serialization. It's not the validation that's wrong - `cargo auditable` does genuinely write data with a cyclic dependency. That's a bug, and I'll be fixing it in the coming days. Thanks again for the nice minimized testcase!

**Comment by Shnatsel** [comment]
Fix merged: https://github.com/rust-secure-code/cargo-auditable/pull/130

I'll ship a release with it in the next few days.

**Comment by Shnatsel** [comment]
`cargo auditable` v0.6.2 with the fix has been published to crates.io
