### ISSUE TITLE
cargo-audit hangs with "Blocking waiting for file lock on package cache"

### ISSUE THREAD

**Issue by vext01** [rustsec/rustsec#1050]
If I clone [this repo](https://github.com/softdevteam/cactus) afresh, and run `cargo audit`:

```
$ cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 575 security advisories (from /home/vext01/.cargo/advisory-db)
    Updating crates.io index
    Blocking waiting for file lock on package cache
```

And it sits like that indefinitely...

There is no other cargo process running for the repo. No LSP or anything like that. I can reproduce this on both Debian and OpenBSD.

Using `strace` I see:
```
statx(AT_FDCWD, "Cargo.lock", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffe061f5360) = -1 ENOENT (No such file or directory)
```

Which got me thinking about `Cargo.lock`... If I run `cargo generate-lockfile` first, then `cargo audit` doesn't block.

So if cargo-audit requires a `Cargo.lock`, then should it make one automatically, or if it can't at least exit with a message like "please run `cargo generate-lockfile`"?

**Comment by Shnatsel** [comment]
Riiiight, it deadlocks with `cargo`. Thanks for the report, that's definitely a bug.

This only affects `rustsec` v0.28.3, so if you force v0.28.2 you can avoid the bug (and maybe run into stale git lockfile instead. Locking is hard :cry: )

**Comment by vext01** [comment]
Thanks for the fix!

(I see there were some clap migration annoyances. As it happens I migrated one of my programs to the new clap the other day. Don't know if the commit may help? https://git.sr.ht/~vext01/tabr/commit/3c98f93743c42bd541b77dff836d9240c3d8a190#src/main.rs)

**Comment by tarcieri** [comment]
I've done the migration in other projects, just haven't gotten around to this one
