### ISSUE TITLE
cargo install fails due to broken dependency -- no Cargo.lock present

### ISSUE THREAD

**Issue by surban** [rustsec/rustsec#1070]
cargo install fails due to some build error in a dependency.

Maybe adding a Cargo.lock file would be helpful to avoid such issues in the future?
Users would then be able to specify the `--locked` option to use a known working dependency version tree.

    $ cargo install cargo-audit
        Updating crates.io index
      Downloaded cargo-audit v0.18.3
      Downloaded 1 crate (50.8 KB) in 0.26s
      Installing cargo-audit v0.18.3
        Updating crates.io index
      Downloaded gix-lock v11.0.0
      Downloaded gix-packetline-blocking v0.16.6
      Downloaded gix-ignore v0.9.0
      Downloaded gix-macros v0.1.0
      Downloaded unicode-bom v2.0.3
      Downloaded faster-hex v0.8.2
      Downloaded gix-worktree-state v0.4.0
      Downloaded gix-refspec v0.19.0
      Downloaded gix-revision v0.23.0
      Downloaded gix-filter v0.6.0
      Downloaded gix-attributes v0.20.0
      Downloaded gix-pathspec v0.4.0
      Downloaded gix v0.55.2
      Downloaded async-compression v0.4.5
      Downloaded tame-index v0.8.0
      Downloaded gix-ref v0.38.0
      Downloaded gix-negotiate v0.9.0
      Downloaded gix-index v0.26.0
      Downloaded gix-worktree v0.27.0
      Downloaded rustsec v0.28.4
      Downloaded gix-submodule v0.5.0
      Downloaded gix-discover v0.26.0
      Downloaded gix-glob v0.14.0
      Downloaded gix-config v0.31.0
      Downloaded gix-odb v0.54.0
      Downloaded gix-packetline v0.16.7
      Downloaded gix-path v0.10.0
      Downloaded gix-hashtable v0.4.0
      Downloaded gix-prompt v0.7.0
      Downloaded gix-object v0.38.0
      Downloaded rustix v0.38.25
      Downloaded prodash v26.2.2
      Downloaded os_str_bytes v6.6.1
      Downloaded gix-traverse v0.34.0
      Downloaded gix-transport v0.38.0
      Downloaded gix-tempfile v11.0.0
      Downloaded gix-sec v0.10.0
      Downloaded gix-revwalk v0.9.0
      Downloaded gix-protocol v0.41.1
      Downloaded gix-pack v0.44.0
      Downloaded gix-features v0.36.0
      Downloaded gix-date v0.8.0
      Downloaded gix-commitgraph v0.22.0
      Downloaded gix-actor v0.28.0
      Downloaded fs-err v2.11.0
      Downloaded eyre v0.6.9
      Downloaded bstr v1.8.0
      Downloaded gix-config-value v0.14.0
      Downloaded gix-hash v0.13.1
      Downloaded gix-credentials v0.21.0
      Downloaded gix-command v0.2.10
      Downloaded gix-fs v0.8.0
      Downloaded gix-diff v0.37.0
      Downloaded gix-url v0.25.1
      Downloaded 54 crates (3.7 MB) in 1.31s
       Compiling proc-macro2 v1.0.69
       Compiling unicode-ident v1.0.12
       Compiling libc v0.2.150
       Compiling autocfg v1.1.0
       Compiling cfg-if v1.0.0
       Compiling serde v1.0.193
       Compiling memchr v2.6.4
       Compiling once_cell v1.18.0
       Compiling thiserror v1.0.50
       Compiling regex-syntax v0.8.2
       Compiling crossbeam-utils v0.8.16
       Compiling bytes v1.5.0
       Compiling scopeguard v1.2.0
       Compiling adler v1.0.2
       Compiling smallvec v1.11.2
       Compiling crc32fast v1.3.2
       Compiling parking_lot_core v0.9.9
       Compiling crossbeam-queue v0.3.8
       Compiling rayon-core v1.12.0
       Compiling gix-trace v0.1.3
       Compiling itoa v1.0.9
       Compiling either v1.9.0
       Compiling same-file v1.0.6
       Compiling prodash v26.2.2
       Compiling sha1_smol v1.0.0
       Compiling hashbrown v0.14.2
       Compiling bitflags v2.4.1
       Compiling powerfmt v0.2.0
       Compiling time-core v0.1.2
       Compiling num_threads v0.1.6
       Compiling home v0.5.5
       Compiling miniz_oxide v0.7.1
       Compiling rustix v0.38.25
       Compiling linux-raw-sys v0.4.11
       Compiling walkdir v2.4.0
       Compiling time-macros v0.2.15
       Compiling equivalent v1.0.1
       Compiling pin-project-lite v0.2.13
       Compiling tinyvec_macros v0.1.1
       Compiling fastrand v2.0.1
       Compiling tracing-core v0.1.32
       Compiling tinyvec v1.6.0
       Compiling futures-core v0.3.29
       Compiling percent-encoding v2.3.0
       Compiling unicode-bidi v0.3.13
       Compiling syn v1.0.109
       Compiling log v0.4.20
       Compiling spin v0.9.8
       Compiling untrusted v0.9.0
       Compiling futures-task v0.3.29
       Compiling form_urlencoded v1.2.0
       Compiling fnv v1.0.7
       Compiling memoffset v0.9.0
       Compiling crossbeam-epoch v0.9.15
       Compiling lock_api v0.4.11
       Compiling num-traits v0.2.17
       Compiling slab v0.4.9
       Compiling gix-utils v0.1.5
       Compiling static_assertions v1.1.0
       Compiling futures-util v0.3.29
       Compiling unicode-bom v2.0.3
       Compiling pin-utils v0.1.0
       Compiling http v0.2.11
       Compiling futures-channel v0.3.29
       Compiling rustls v0.21.9
       Compiling ryu v1.0.15
       Compiling flate2 v1.0.28
       Compiling futures-sink v0.3.29
       Compiling httparse v1.8.0
       Compiling futures-io v0.3.29
       Compiling aho-corasick v1.1.2
       Compiling winnow v0.5.19
       Compiling kstring v2.0.0
       Compiling try-lock v0.2.4
       Compiling crossbeam-channel v0.5.8
       Compiling semver v1.0.20
       Compiling version_check v0.9.4
       Compiling quote v1.0.33
       Compiling indexmap v2.1.0
       Compiling want v0.3.1
       Compiling encoding_rs v0.8.33
       Compiling tower-service v0.3.2
       Compiling base64 v0.21.5
       Compiling syn v2.0.39
       Compiling crossbeam-deque v0.8.3
       Compiling httpdate v1.0.3
       Compiling openssl-probe v0.1.5
       Compiling proc-macro-error-attr v1.0.4
       Compiling mime v0.3.17
       Compiling unicode-normalization v0.1.22
       Compiling ipnet v2.9.0
       Compiling arrayvec v0.7.4
       Compiling serde_json v1.0.108
       Compiling crossbeam v0.8.2
       Compiling rustls-pemfile v1.0.4
       Compiling uluru v3.0.0
       Compiling http-body v0.4.5
       Compiling proc-macro-error v1.0.4
       Compiling rustls-native-certs v0.6.3
       Compiling clru v0.6.1
       Compiling arc-swap v1.6.0
       Compiling fixedbitset v0.4.2
       Compiling indexmap v1.9.3
       Compiling petgraph v0.6.4
       Compiling fs-err v2.11.0
       Compiling eyre v0.6.9
       Compiling camino v1.1.6
       Compiling idna v0.4.0
       Compiling rayon v1.8.0
       Compiling gimli v0.28.0
       Compiling regex-syntax v0.6.29
       Compiling object v0.32.1
       Compiling hashbrown v0.12.3
       Compiling indenter v0.3.3
       Compiling heck v0.4.1
       Compiling rustc-demangle v0.1.23
       Compiling os_str_bytes v6.6.1
       Compiling overload v0.1.1
       Compiling btoi v0.4.3
       Compiling cc v1.0.83
       Compiling memmap2 v0.7.1
       Compiling mio v0.8.9
       Compiling socket2 v0.5.5
       Compiling num_cpus v1.16.0
       Compiling getrandom v0.2.11
       Compiling parking_lot v0.12.1
       Compiling gix-sec v0.10.0
       Compiling socket2 v0.4.10
       Compiling filetime v0.2.22
       Compiling regex-automata v0.4.3
       Compiling io-close v0.3.7
       Compiling unicode-xid v0.2.4
       Compiling tokio v1.34.0
       Compiling lazy_static v1.4.0
       Compiling sharded-slab v0.1.7
       Compiling clap_lex v0.2.4
       Compiling nu-ansi-term v0.46.0
       Compiling atty v0.2.14
       Compiling tracing-log v0.2.0
       Compiling twox-hash v1.6.3
       Compiling tempfile v3.8.1
       Compiling thread_local v1.1.7
       Compiling zeroize v1.7.0
       Compiling termcolor v1.4.0
       Compiling binfarce v0.2.1
       Compiling owo-colors v3.5.0
       Compiling textwrap v0.16.0
       Compiling bitflags v1.3.2
       Compiling ident_case v1.0.1
       Compiling topological-sort v0.2.2
       Compiling strsim v0.10.0
       Compiling wait-timeout v0.2.0
       Compiling ring v0.17.5
       Compiling backtrace v0.3.69
       Compiling tracing-log v0.1.4
       Compiling miniz_oxide v0.6.2
       Compiling canonical-path v2.0.2
       Compiling auditable-extract v0.3.2
       Compiling regex-automata v0.1.10
       Compiling jwalk v0.8.1
       Compiling addr2line v0.21.0
       Compiling matchers v0.1.0
       Compiling synstructure v0.12.6
       Compiling bstr v1.8.0
       Compiling regex v1.10.2
       Compiling color-eyre v0.6.2
       Compiling maybe-async v0.2.7
       Compiling clap_derive v3.2.25
       Compiling abscissa_derive v0.6.0
       Compiling gix-command v0.2.10
       Compiling serde_derive v1.0.193
       Compiling thiserror-impl v1.0.50
       Compiling tracing-attributes v0.1.27
       Compiling gix-macros v0.1.0
       Compiling async-compression v0.4.5
       Compiling gix-path v0.10.0
       Compiling gix-validate v0.8.0
       Compiling gix-chunk v0.4.4
       Compiling gix-quote v0.4.7
       Compiling gix-bitmap v0.2.7
       Compiling tracing v0.1.40
       Compiling gix-config-value v0.14.0
       Compiling tokio-util v0.7.10
       Compiling tracing-subscriber v0.3.18
       Compiling clap v3.2.25
       Compiling gix-prompt v0.7.0
       Compiling h2 v0.3.22
       Compiling hyper v0.14.27
       Compiling faster-hex v0.8.2
       Compiling deranged v0.3.9
       Compiling url v2.4.1
       Compiling toml_datetime v0.6.5
       Compiling serde_spanned v0.6.4
       Compiling serde_urlencoded v0.7.1
       Compiling smol_str v0.2.0
       Compiling cvss v2.0.0
       Compiling toml v0.5.11
       Compiling secrecy v0.8.0
       Compiling platforms v3.2.0
       Compiling gix-hash v0.13.1
       Compiling gix-packetline v0.16.7
       Compiling gix-packetline-blocking v0.16.6
       Compiling toml_edit v0.19.15
       Compiling toml_edit v0.21.0
    error[E0004]: non-exhaustive patterns: `faster_hex::Error::Overflow` not covered
      --> /home/surban/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gix-hash-0.13.1/src/object_id.rs:57:86
       |
    57 | ...| match err {
       |            ^^^ pattern `faster_hex::Error::Overflow` not covered
       |
    note: `faster_hex::Error` defined here
      --> /home/surban/.cargo/registry/src/index.crates.io-6f17d22bba15001f/faster-hex-0.8.2/src/error.rs:5:5
       |
    2  | pub enum Error {
       | --------------
    ...
    5  |     Overflow,
       |     ^^^^^^^^ not covered
       = note: the matched value is of type `faster_hex::Error`
    help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown
       |
    61 ~                             },
    62 +                             faster_hex::Error::Overflow => todo!()
       |
    
    error[E0004]: non-exhaustive patterns: `faster_hex::Error::Overflow` not covered
       --> /home/surban/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gix-hash-0.13.1/src/prefix.rs:117:28
        |
    117 |         .map_err(|e| match e {
        |                            ^ pattern `faster_hex::Error::Overflow` not covered
        |
    note: `faster_hex::Error` defined here
       --> /home/surban/.cargo/registry/src/index.crates.io-6f17d22bba15001f/faster-hex-0.8.2/src/error.rs:5:5
        |
    2   | pub enum Error {
        | --------------
    ...
    5   |     Overflow,
        |     ^^^^^^^^ not covered
        = note: the matched value is of type `faster_hex::Error`
    help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown
        |
    119 ~             faster_hex::Error::InvalidLength(_) => panic!("This is already checked"),
    120 ~             faster_hex::Error::Overflow => todo!(),
        |
    
    For more information about this error, try `rustc --explain E0004`.
       Compiling quitters v0.1.0
    error: could not compile `gix-hash` (lib) due to 2 previous errors
    warning: build failed, waiting for other jobs to finish...
    error: failed to compile `cargo-audit v0.18.3`, intermediate artifacts can be found at `/tmp/cargo-installxrtcXG`.
    To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

**Comment by surban** [comment]
Cargo.lock is indeed present in the parent folder. I was not aware that Cargo takes this into account.

**Comment by Shnatsel** [comment]
Thank you for the report!

The issue was caused by the `faster-hex` crate publishing a point release with a semver-breaking change. The problematic release has now been yanked, and `cargo audit` compiles again.

Also, I've inspected the tarball for `cargo audit` uploaded to crates.io and it does contain the `Cargo.lock` file.
