### ISSUE TITLE
cargo-audit: Audit crate project status

### ISSUE THREAD

**Issue by nickspurry** [rustsec/rustsec#1089]
The crates.io registry is 'polluted' by projects that are no longer under active development.

It would be great if cargo-audit could warn about the use of projects that are no longer being developed or maintained, regardless of whether they have a declared vulnerability.

**Comment by tarcieri** [comment]
We already track unmaintained crates, which are surfaced as a warning (that can be turned into a hard error) by `cargo-audit`.

Here's some more information: https://github.com/rustsec/advisory-db/blob/main/HOWTO_UNMAINTAINED.md
