### ISSUE TITLE
cargo deny check fails to pull advisory.db (but cargo audit works)

### ISSUE THREAD

**Issue by SeanEClarke** [rustsec/rustsec#1151]
When running `cargo deny check` I get:

```
 [ERROR] failed to fetch advisory database https://github.com/RustSec/advisory-db: An IO error occurred when talking to the server: error sending request for url (https://github.com/RustSec/advisory-db/info/refs?service=git-upload-pack)
```

however, when I run `cargo audit` it works fine:
```
cargo audit         
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 614 security advisories (from /home/<redacted>/.cargo/advisory-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (385 crate dependencies)
```

I have checked (and removed etc.) the ` ~/.cargo/advisory-db` and any .lock's etc.

Is there any verbose or debug logging I can enable?

- running Rust 1.77 stable toolchain on Debian

**Comment by amousset** [comment]
Seems identical to https://github.com/rustsec/advisory-db/issues/1923 / https://github.com/EmbarkStudios/cargo-deny/issues/641

**Comment by amousset** [comment]
Should be fixed now (https://github.com/Byron/gitoxide/issues/1328#issuecomment-2016486540).

**Comment by SeanEClarke** [comment]
can confirm it is now fixed
