### ISSUE TITLE
serde-yaml is now deprecated

### ISSUE THREAD

**Issue by dupgit** [rustsec/rustsec#1168]
[serde-yaml](serde-yaml) is now unmaintained and archived on github. Shouldn't `cargo audit` raise a warning when detecting usage of it ?

**Comment by tarcieri** [comment]
Yes, it should. Can you please provide an example `Cargo.lock` where you think it isn't being detected?

**Comment by dupgit** [comment]
I believe that commit [ebce87b916](https://gitlab.com/delhomme/rversions/-/commit/ebce87b9168b180d4e55069033d42c9548add7ef) of [rversions](https://gitlab.com/delhomme/rversions) project has such a `Cargo.lock` file:

``` bash
$ git log -1
commit ebce87b9168b180d4e55069033d42c9548add7ef
…

$ git grep 'serde_yaml' Cargo.toml
Cargo.toml:serde_yaml = "0.9.16"

$ git grep -A 1 'name = "serde_yaml"'
Cargo.lock:name = "serde_yaml"
Cargo.lock-version = "0.9.34+deprecated"

$ cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 617 security advisories (from /home/dup/.cargo/advisory-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (172 crate dependencies)
Crate:     h2
Version:   0.3.25
Title:     Degradation of service in h2 servers with CONTINUATION Flood
Date:      2024-04-03
ID:        RUSTSEC-2024-0332
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0332
Solution:  Upgrade to ^0.3.26 OR >=0.4.4
Dependency tree:
h2 0.3.25
├── reqwest 0.11.27
│   └── rversions 1.2.11
└── hyper 0.14.28
    ├── reqwest 0.11.27
    └── hyper-tls 0.5.0
        └── reqwest 0.11.27

error: 1 vulnerability found!
```

Has you can see the h2 RUSTSEC-2024-0332 advisory is correctly trapped but it seems ok for serde_yaml to be in `0.9.34+deprecated`

**Comment by tarcieri** [comment]
Aah, we haven't actually filed an advisory for `serde-yaml` yet: https://github.com/rustsec/advisory-db/issues/1925

**Comment by dupgit** [comment]
Thanks :-)
