### ISSUE TITLE
The latest stable version of cargo-audit does not build with the latest stable compiler

### ISSUE THREAD

**Issue by kornelski** [rustsec/rustsec#1240]
The lockfile in 0.20.0 requires a version of the `time` crate that [rustc has broken](https://github.com/rust-lang/rust/issues/127343).

This broke my CI jobs that use `--locked` when building cargo-audit. Can you make a release of the stable version with an updated lockfile? 

I know there's a newer pre-release version, but I'd rather not use unstable versions, and the next release seems to be already taking quite a long time.

**Comment by tarcieri** [comment]
FWIW removing `--locked` should fix the problem in the interim

Yes, I'll try to finish out the current crates and get a real release out soon. #1206 is the only blocker.

**Comment by Shnatsel** [comment]
How about I check out the git state of 0.20.0 and publish 0.20.1 with the only change being a bumped `Cargo.lock`?

**Comment by tarcieri** [comment]
That's probably ok if you tag the result

**Comment by Shnatsel** [comment]
Done. I've verified that `cargo install --locked cargo-audit` works on the latest rustc.
