### ISSUE TITLE
Add the Ability to Filter out Dev Dependencies when Using `cargo lock list`

### ISSUE THREAD

**Issue by ShiromMakkad** [rustsec/rustsec#1253]
I'd like to only see runtime dependencies with `cargo lock list` when running from the CLI. Is this possible? Thanks.

**Comment by Shnatsel** [comment]
No, this is not possible based on the `Cargo.lock` file. You need either `cargo tree` for that (for human readable format) or `cargo metadata` plus [`krates`](https://crates.io/crates/krates) for the machine-readable data.
