### ISSUE TITLE
WebAssembly component support for `cargo-audit` 

### ISSUE THREAD

**Issue by TitusVM** [rustsec/rustsec#1255]
Hi all!

I'm trying to make an auditable WebAssembly component that I build with [`cargo-auditable`](https://github.com/rust-secure-code/cargo-auditable) and convert with [`wasm-tools component new`](https://github.com/bytecodealliance/wasm-tools), however, it seems as though `cargo-audit` is incapable of parsing the binary after the conversion. 

My component is defined as follows:
```rust
// src/lib.rs

wit_bindgen::generate!({
    path: "wit/component.wit",
    exports: {
        "test:guest/foo": Foo
    }
});

struct Foo;

impl exports::test::guest::foo::Guest for Foo {
    fn select_nth(x: Vec<String>, i: u32) -> String {
        x.into_iter().nth(i as usize).expect("Could not get value.")
    }
}
```
```wit
// wit/component.wit

package test:guest;

interface foo {
    // Selects the item in position n within list x
    select-nth: func(x: list<string>, n: u32) -> string;
}

world guest {
    export foo;
}
```
I build with `cargo-auditable` ([9d718af ](https://github.com/rust-secure-code/cargo-auditable/commit/9d718af5c94a5e8da335306a2f2868865097b2e9)) 
`./cargo-auditable auditable build --target=wasm32-unknown-unknown`

(If we run a `cargo-audit` on the generated binary everything works as expected).

I convert it to a wasm component using `wasm-tools 1.218.0`:
`wasm-tools component new ./target/.../component.wasm -o component.wasm`

If I try running `cargo-audit-audit 0.21.0-pre.0` on this binary:
`./cargo-audit audit bin ./component.wasm`

Resulting in:
```txt
error: parse error: could not extract dependencies from binary component.wasm
Caused by:
  -> Failed to parse the binary: Malformed executable file
  -> Malformed executable file
```

Is this expected behaviour or am I doing something wrong in the process? Any feedback would be greatly appreciated!

**Comment by Shnatsel** [comment]
Could you post the .wit file?

The first step is to feed it to https://www.wa2.io/ and see if the custom section that `cargo auditable` has embedded is still there.

**Comment by TitusVM** [comment]
Do you mean a different .wit from the one I posted in the OP? 

I put the component binary into the analyzer and it looks like the "dep-v0" section is still there! 
![image](https://github.com/user-attachments/assets/d3d39864-483e-4d1e-90b3-578e76dd4749)

**Comment by TitusVM** [comment]
I've been looking at the cargo-auditable crate and more specifically at the way the dependencies are extracted from the binary. I found that the function [raw_auditable_data_wasm()](https://github.com/rust-secure-code/cargo-auditable/blob/9d718af5c94a5e8da335306a2f2868865097b2e9/auditable-extract/src/wasm.rs#L7) used to extract the dependency section, may be at fault for the Malformed Executable error. The error triggers on this [line](https://github.com/rust-secure-code/cargo-auditable/blob/9d718af5c94a5e8da335306a2f2868865097b2e9/auditable-extract/src/wasm.rs#L19) where:

```rust
let payload = match parser
    .parse(input, true)
    .map_err(|_| Error::MalformedFile)?
```

throws an error because it reaches the end of the file. I added some debug prints and this is the error thrown by wasmparser:
```txt
[DEBUG] Error: BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 1667134, needed_hint: None } }```
```
I also tried listing the payloads and there are only two sections found before it reaches EOF:
```txt
[DEBUG] Size of input: 1667462
[DEBUG] Found section Version { num: 13, encoding: Component, range: 0..8 }
[DEBUG] Found section ModuleSection { range: 12..1667131 }
[DEBUG] Error: BinaryReaderError { inner: BinaryReaderErrorInner { message: "unexpected end-of-file", offset: 1667134, needed_hint: None } }
```
Could it be that the custom sections are hidden inside of the ModuleSection and can therefore not be read by the manual offset loop?

I tried extracting the data using wasmparser directly with this snippet:
```rust
let buf: Vec<u8> = std::fs::read("./component.wasm").unwrap();
println!("[DEBUG] is empty {:?}", buf.is_empty());
for payload in Parser::new(0).parse_all(&buf) {
    match payload? {
        Payload::CustomSection(s) => {
            println!("[DEBUG] Found custom section");
            if s.name() == ".dep-v0" {
                let decomp = decompress_to_vec_zlib_with_limit(s.data(), 1024 * 8 * 8).unwrap();
                println!("Decompressed data: {:?}", String::from_utf8(decomp));
            }
        }
        _other => {
            // println!("found payload {:?}", _other);
        }
    }
}
```

And that works - could this be used in the previously mentioned function rather than the manual offset loop?

**Comment by Shnatsel** [comment]
Thanks a lot for investigating this!

Yes, that looks like better code to me. I'd be happy to merge a PR that changes the manual loop to this. The initial idea was not to even parse the sections that weren't relevant, so that we don't hit an error on a completely unrelated section that the parser doesn't know how to handle, but given this issue that approach was clearly wrong.

**Comment by TitusVM** [comment]
I'm happy to contribute! I'll get right on it

**Comment by Shnatsel** [comment]
I've published a version with the fix to crates.io. Please `cargo install cargo-audit --version=0.21.0-pre.0`  (without `--locked`) to get a version that works with WASM components.

Thank you @TitusVM for contributing the fix!
