### ISSUE TITLE
Trojan:Win32/Sabsik.TE.A!ml alert from defender while installing cargo-audit

### ISSUE THREAD

**Issue by maciejw** [rustsec/rustsec#1292]
Hi,

I started my journey with rust, and its almost an impossible task, I got notifications about trojans malware and other junk, when installing serde, then cargo-tarpaulin, then grcov (its a code coverage that RustRover installs by default), since its impossible to check in a reasonable time, if what I'm installing is indeed a malicious software, I thought hey, maybe rust community has something that tracks vulnerabilities in crates, I started looing for information if crates are scanned with some antivirus software (did not get a definitive answer, but it looks like probably they are not, its scary), then I stumbled upon cargo-audit, and I though ok, lest try it, and then I got a notification, that in some build script (AppData\Local\Temp\cargo-installfUYClO\release\build\num-traits-aa20f98810e52bb1\build-script-build.exe) there is a trojan (kind of hilarious, and scary at the same time), I know it can be false positive, but I really dont want to do forensic analysis of every executable I'm getting from crates.io, am I missing something here? am I crazy?
MS scans programs that you can install using winget, they are also scanning nuget packages, I dont think nodejs NPM packages are scanned, but they have something similar to cargo audit, deno (that will replace nodejs) went one step further, they are sandboxing everything, and when someone is using a system api, user has to explicitly give a permission for it, I know its more tricky in rust, but the trend is quite obvious. 
If rust is depicted as a safe option for writing software in terms of memory management, and then if its not save to use any crate, and you have to write everything from scratch to be sure its save, then it defeats the purpose of reusable software. if you want to develop reliable software you have to have some kind of foundation you know its safe.
I'm asking more general question, lets say I want to use rust in a corporate environment, are there any guidelines from rustsec how to deal with it? I know for a fact, that it will be disallowed without tools like jfrog artifactory and xray. 
If I want to develop or learn rust privately, does it mean that I have to setup my own artifactory server then pay for xray subscription and setup proxy feed and then use crates.io? even if I would do it, its still a bad solution because with such dependency graphs like in rust we will end up eventually with something like NPM did, with left-pad in 2016, where some developer deleted a package most packages depended on, and event-stream in 2018 where Crypto-coin-stealing code ended up in a package that had 2m downloads per week, rust is going in the same direction, small packages like nodejs, one infected package deep in dependency tree makes a lot of packages unusable... 
This is why something like Dotnet Foundation or Apache exists, so there is an open source software that you can rely on, there is such initiative with Rust foundation in regards to standard library, but are there any plans to to something with crates.io also? maybe there is something like this but I'm not aware of it yet.
![image](https://github.com/user-attachments/assets/997ae30f-fb39-4225-a3ea-238dc07c4274)

**Comment by Shnatsel** [comment]
Rust Foundation's Security Initiative does indeed perform continuous scans of crates.io for malicious packages using a variety of heuristics.

For ensuring the absence of backdoors in dependencies you can use [cargo-vet](https://github.com/mozilla/cargo-vet) or [cargo-crev](https://github.com/crev-dev/cargo-crev).

cargo-audit tracks software vulnerabilities (think CVEs), not instances of malicious code. I'm going to close this since this is not actionable for cargo-audit.

**Comment by maciejw** [comment]
thanks for a quick answer, I've checked few thing and those reports from defender I got, were only present, while I was using `stable-x86_64-pc-windows-gnu` toolchain, I tried `stable-x86_64-pc-windows-msvc` instead and it looks like defender stopped complaining, maybe it will help someone.
