### ISSUE TITLE
Dependency tree cutoff early

### ISSUE THREAD

**Issue by Nemo157** [rustsec/rustsec#289]
For some reason when running `cargo audit` on https://github.com/voxl-rs/voxl (at `82de792604349e0162f836230ae899a8e7533b1e`) it doesn't show the full dependency tree for `image 0.18.0`:

```console
> cargo audit
[...]
Dependency tree:
image 0.18.0

> cargo tree -i image:0.18.0
image v0.18.0
└── noise v0.6.0
    └── voxl v0.0.1 (/tmp/tmp.O2CDdVzoRi/voxl)

> cargo audit --version
cargo-audit 0.13.1
```

I thought it might be because `voxl` also has a direct `image 0.23` dependency, but trying to setup a similar situation in a test project I couldn't reproduce the issue.

**Comment by RalfJung** [comment]
I think I am running into the same problem -- some of the dependency trees I get on https://github.com/freifunk-saar/ff-node-monitor/tree/477aabd4b6a4a673f8cd187a9a28daccaa38eebd are pretty useless:
```
Dependency tree: 
hyper 0.10.16
```
My crate does not depend on hyper directly, so this tells me very little.

```
Dependency tree: 
aes-soft 0.6.4
└── aes 0.6.0
    └── aes-gcm 0.8.0
        └── cookie 0.11.4
```
My crate does not appear in that tree, so not sure what to do with it.

**Comment by tarcieri** [comment]
@RalfJung that does indeed look quite wrong.

The issue appears to be related to the presence of different versions of the same dependency in the same lockfile. For example, `cookie` in the above dependency tree is a dependency of `cookie_store`:

```
[[package]]
name = "cookie_store"
version = "0.7.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "46750b3f362965f197996c4448e4a0935e791bf7d6631bfce9ee0af3d24c919c"
dependencies = [
 "cookie 0.12.0",
 "failure",
 "idna 0.1.5",
 "log 0.4.17",
 "publicsuffix",
 "serde",
 "serde_json",
 "time",
 "try_from",
 "url 1.7.2",
]
```

However if I look at your lockfile in `cargo lock tree`, I see:

```
│   ├── cookie_store 0.7.0
│   │   ├── try_from 0.3.2
│   │   ├── time 0.1.43
│   │   ├── serde_json 1.0.81
│   │   ├── serde 1.0.137
│   │   ├── publicsuffix 1.5.6
│   │   └── failure 0.1.8
│   │       ├── failure_derive 0.1.8
│   │       │   └── synstructure 0.12.6
│   │       └── backtrace 0.3.65
│   │           ├── rustc-demangle 0.1.21
│   │           ├── object 0.28.4
│   │           ├── miniz_oxide 0.5.1
│   │           ├── libc 0.2.126
│   │           ├── cc 1.0.73
│   │           └── addr2line 0.17.0
│   │               └── gimli 0.26.1
```

All of the dependencies with explicit versions (`cookie`, `idna`, `log`, `url`) are missing.

**Comment by tarcieri** [comment]
I believe #568 should address the issue

**Comment by tarcieri** [comment]
I installed the `cargo lock` CLI with these changes and confirmed `cargo lock tree` now looks correct for https://github.com/freifunk-saar/ff-node-monitor/tree/477aabd4b6a4a673f8cd187a9a28daccaa38eebd
