### ISSUE TITLE
Unable to fetch advisory database: "an unknown git error occurred"

### ISSUE THREAD

**Issue by maxburke** [rustsec/rustsec#324]
Hello,

When running cargo-audit I'm getting this error message:

```
$ cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
error: couldn't fetch advisory database: git operation failed: an unknown git error occurred
```

If I fetch advisory-db into a directory and pass `--stale` I still receive the same error message.

**Comment by tarcieri** [comment]
That's not a lot to go on and you're the only person reporting this error. Is there anything particularly unusual about your local environment, particularly in relation to git?

**Comment by maxburke** [comment]
@tarcieri I noticed the same issue in the cargo-deny project too: https://github.com/EmbarkStudios/cargo-deny/issues/330

I don't know what other ways there are to get more information; is there a verbose flag?

**Comment by tarcieri** [comment]
If it's on an M1, I can try it on mine and see if that's in some way related

**Comment by maxburke** [comment]
I was seeing this on Ubuntu 20.04 as well

**Comment by tarcieri** [comment]
If you're seeing it on two platforms, it might be related to some sort of shared dotfiles you have on both. Do you have anything odd in `.gitconfig`?

**Comment by PureW** [comment]
Unclear if this is related but I started seeing
```
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
error: couldn't fetch advisory database: git operation failed: failed to authenticate when downloading repository
attempted ssh-agent authentication, but none of the usernames `git` succeeded
```
today in CI, no changes from last week.

**Comment by tarcieri** [comment]
It's unrelated. See #331

**Comment by tarcieri** [comment]
@PureW that looks unrelated to this issue in particular, which is "an unknown git error occurred"

Can you open a new issue?

**Comment by Byter09** [comment]
Just chiming in to report, that we also see this pretty often in our GitLab CI. I also encounter this locally.

```
$ cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
error: couldn't fetch advisory database: git operation failed: reference 'refs/heads/main' not found; class=Reference (4); code=NotFound (-3)
```

We're seeing this for like a week now.


Some local system info that might help figure this out:
```
$ uname -a
Linux BTR-PC 5.10.19-1-MANJARO #1 SMP PREEMPT Fri Feb 26 11:38:34 UTC 2021 x86_64 GNU/Linux

$ git --version
git version 2.30.1

$ cargo audit --version
cargo-audit 0.14.0

$ cargo --version
cargo 1.50.0 (f04e7fab7 2021-02-04)

$ rustc --version
rustc 1.50.0 (cb75ad5db 2021-02-10)
```

I can get you CI specific information if necessary.

**Comment by tarcieri** [comment]
Note that if you're seeing errors like:

```
error: couldn't fetch advisory database: git operation failed: reference 'refs/heads/main' not found; class=Reference (4); code=NotFound (-3)
```

...that's an unrelated issue. See: #331.

The solution to that is to reinstall `cargo-audit`.

**Comment by Byter09** [comment]
Yeah I removed my comment when I saw that. We rebuilt our CI image and cleared all runner caches just to be sure. :)

**Comment by XopheD** [comment]
I met the same message on my macbook.

```
cargo -v audit 
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
error: couldn't fetch advisory database: git operation failed: an unknown git error occurred
```

My current workaround is to `git clone`  the advisory database in my  home `.cargo` directory and I regularly `git pull` to get the last updates. 

Then, using `cargo audit -n` seems to work fine.

But it is not the simplest way...

**Comment by tarcieri** [comment]
Can anyone who can reproduce the "an unknown git error occurred" message run a tool like `strace` or `ktrace` and attempt to determine what libgit2 is attempting to do when this error occurs? Are there any notable system calls that are erroring out? What is the last thing it's accessing?

**Comment by dr0ps** [comment]
I had this issue today. And it seems at some point in the past the advisory changed from using the "master" branch to "main". To fix this issue I only needed to go to ~/.cargo/advisory-db and do a `git checkout main`. Now cargo audit works again.

**Comment by q2333gh** [comment]
me to . just want to totally disable it .  some good guy in the rust forum says:

[jofas](https://users.rust-lang.org/u/jofas)
[3h](https://users.rust-lang.org/t/how-to-disable-advisory-also-rust-audit-forever/99774/2?u=q2333gh)
You can stop cargo deny from downloading the advisory database by running it with the [--ofline 1](https://embarkstudios.github.io/cargo-deny/cli/common.html#--offline) or more specifically the [-d/--disable-fetch](https://embarkstudios.github.io/cargo-deny/cli/check.html#-d---disable-fetch) CLI options. For cargo audit you should be able to avoid downloading the db with the -n/--no-fetch CLI option.

**Comment by q2333gh** [comment]
but i fail to disable it . hah.

**Comment by q2333gh** [comment]
i also tried this :
```bash
rm -rf ~/.cargo/advisory-db/*
rm -rf ~/.cargo/advisory-db.rustsec.lock 
```
and it works sometime.
