### ISSUE TITLE
Pre-release handling regression

### ISSUE THREAD

**Issue by tarcieri** [RustSec/rustsec#349]
RustSec/rustsec-crate#217 updated the `semver` crate to v0.10, and with it ripped out a lot of vendored code from `semver` v0.9 (as it were, RustSec/rustsec-crate#244 has since bumped `semver` to v0.11)

This likely caused a regression of how prereleases are handled. See:

- https://github.com/RustSec/cargo-audit/issues/17
- https://github.com/RustSec/cargo-audit/issues/30
- https://github.com/steveklabnik/semver/issues/172

**Comment by Shnatsel** [comment]
I am working on fixing this. A solution for this arrives as a side effect of the OSV integration work, see #366

**Comment by Shnatsel** [comment]
The fix has shipped in `rustsec` v0.24 and cargo-audit v0.15
