### ISSUE TITLE
platforms-crate: out-of-sync with the list referenced in its documentation.

### ISSUE THREAD

**Issue by ebeasant-arm** [rustsec/rustsec#350]
The list maintained at https://doc.rust-lang.org/nightly/rustc/platform-support.html includes a couple of Tier-1 and Tier-2 platforms that are not recognised (in 1.1.0) or are in different tiers compared with platforms-crate. This is given as the reference list for the Platforms crate.

When building crates that check the current platform (find or guess_current) against the list, this is causing failures on some devices.

A re-sync pf platforms-crate to the master list (above) would fix this, and a release would be really helpful.

**Comment by tarcieri** [comment]
PR to update it here (originally by @messanence, thank you!):

https://github.com/RustSec/rustsec/pull/353

**Comment by Shnatsel** [comment]
Fixed by auto-generating the `platforms` crate, see https://github.com/rustsec/rustsec/pull/516
