### ISSUE TITLE
`rust-toolchain` file breaks Rust Analyzer

### ISSUE THREAD

**Issue by Shnatsel** [RustSec/rustsec#370]
TL;DR: the `rust-toolchain` file breaks rust-analyzer, the official IDE solution for Rust. 

Details here: https://github.com/rust-analyzer/rust-analyzer/issues/8906

How necessary is it to have it? Can we get away with having CI run on 1.46, but not have the `rust-toolchain` file in the project?

**Comment by lnicola** [comment]
I think it makes sense to test the MSRV on CI than to force contributors to use an toolchain.

**Comment by tarcieri** [comment]
I guess you can remove it. That seems like an odd breakage in rust-analyzer though...

**Comment by lnicola** [comment]
It breaks RA because we expand proc macros by the means of some code that's copy-pasted from `rustc`.

**Comment by Shnatsel** [comment]
Cool, addressed in #371
