### ISSUE TITLE
Feature request: .auditignore file

### ISSUE THREAD

**Issue by ajeetdsouza** [RustSec/rustsec#383]
The `--ignore` flag in `cargo-audit` is very useful. Things like `dev-dependencies` being unmaintained are trivial issues that don't warrant any action -- but I have to remember to pass the flag everywhere (CI, locally), and anyone who uses my project would also end up wasting time on the same issue.

Instead, if there was an `.auditignore` file, I would list the issues that I'm currently okay with ignoring, and add a comment there so that users know _why_ that vulnerability is being ignored.

**Comment by tarcieri** [comment]
You can accomplish this with an `~/.cargo/audit.toml` file in your project:

https://github.com/RustSec/rustsec/blob/b618859/cargo-audit/audit.toml.example#L6

**Comment by ajeetdsouza** [comment]
Oh, sorry. I didn't know about audit.toml. Thanks!
