### ISSUE TITLE
Can't install cargo audit 

### ISSUE THREAD

**Issue by ggkitsas** [RustSec/rustsec#401]
When trying to `cargo install cargo-audit` ,I get the same error as in https://github.com/RustSec/rustsec/issues/254. 

I tried `cargo install --git https://github.com/RustSec/cargo-audit.git --branch main cargo-audit` without success.

Tried the above in both Rust 1.44 and 1.51.

**Comment by tarcieri** [comment]
Did you get this fixed? If so, what was the problem?
