### ISSUE TITLE
Question: cargo audit job with exit(0)

### ISSUE THREAD

**Issue by zakrush** [rustsec/rustsec#407]
Hi.
Cargo audit is has way to exit job with code 0, if it find vulnerabilityes or errors?
Gitlab jobs failed everytime, bu I needed only json reports and don't fail job if cargo audit found some error.

I think, that --quiet for this, but it didn't help me.

**Comment by tarcieri** [comment]
Code 0 indicates success. It exits with status 1 if a vulnerability is found, or 2 if some other error occurred:

https://github.com/rustsec/rustsec/blob/d0c23fa/cargo-audit/src/commands/audit.rs#L242-L244
