### ISSUE TITLE
`cargo audit` incorrectly checks packages in non-crates.io registries

### ISSUE THREAD

**Issue by timwalls** [rustsec/rustsec#408]
Some of my packages are in a private registry.  I've just discovered that `cargo audit` doesn't realise this and uses the vulnerabilities of public packages if the names happen to match.

For example, I have a package `serial` that is now on version 0.3.1:
```
[package]
name = "serial"
version = "0.3.1"
authors = ["Tim Walls <tim.walls@snowgoons.com>"]
edition = "2018"

# For publishing to our private repository
publish = ["snowgoons-crates"]
```

I have applications that reference this package like this:
```
serial = { version = "0.3", registry = "snowgoons-crates" }
```

These mysteriously started failing their audits when my serial package hit 0.3.1:

```
Crate:         serial
Version:       0.3.1
Warning:       yanked
Dependency tree:
serial 0.3.1
├── printer-svc 0.8.0
└── cash-svc 0.7.9

error: 1 denied warning found!
```

I just realised this is because there is a package of the same name in the crates.io repository, which happened to have its 0.3.1 version yanked: https://crates.io/crates/serial/versions

### TL;DR version
`cargo audit` should recognise when a package is imported from a registry other than `crates.io`.

**Comment by tarcieri** [comment]
Thought we had some other open issues about this but apparently not.

The fix should be fairly straightforward.

**Comment by timwalls** [comment]
Yep, I did have a quick check first and didn't find anything obvious.  I was feeling guilty though that I realise I didn't check with the latest version before opening the Issue (I had 0.14.1 installed) - but just to confirm I have now updated and can reproduce with 0.15.0 as well.


I guess it's something you need to be quite unlucky to run into, so I'm sure not top priority :).  I have worked around it the obvious way (just bumped my `serial` crate to 0.3.2).

Thanks for a super useful tool, by the way (even if I do swear every time it makes my CI/CD pipeline fail ;-).)

**Comment by crepererum** [comment]
Is this technically the same issue as #232? So the common issue is: "non-crates.io crates should be excluded even if the same name exists in crates.io" where "non-crates.io crates" are:

- part of the workspace (#232)
- in a private registry (this issue here)
- (probably also) crates specified via GIT repo or relative file path

**Comment by tarcieri** [comment]
Aha yes, that is definitely a similar issue.

I think the best resolution to this is to associate advisory databases with a particular [`SourceId`](https://docs.rs/cargo-lock/latest/cargo_lock/package/source/struct.SourceId.html) and use that `SourceId` when looking up advisories for a particular package.

**Comment by tarcieri** [comment]
Note that you can use `cargo audit --no-local-crates` to avoid this

**Comment by timwalls** [comment]
That won't avoid the problem with crates in private registries though, will it?

**Comment by crepererum** [comment]
> Note that you can use `cargo audit --no-local-crates` to avoid this

This doesn't seem to work for yanked crates though: If I remove these lines

https://github.com/influxdata/influxdb_iox/blob/5247fee979c3316719dcd61b6c4b529bc0545d3c/.cargo/audit.toml#L53-L55

and run `cargo audit --no-local-crates` I still get:

```console
$ cargo audit --no-local-crates
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 371 security advisories (from /home/mneumann/.cargo/advisory-db)
    Scanning Cargo.lock for vulnerabilities (459 crate dependencies)
Crate:         query
Version:       0.1.0
Warning:       yanked
Dependency tree:
query 0.1.0
├── server_benchmarks 0.1.0
├── server 0.1.0
│   ├── server_benchmarks 0.1.0
│   ├── query_tests 0.1.0
│   │   └── server_benchmarks 0.1.0
│   └── influxdb_iox 0.1.0
├── query_tests 0.1.0
└── influxdb_iox 0.1.0

error: 1 denied warning found!
```

`query` is a local crate within that repo and shouldn't be checked.
