### ISSUE TITLE
Create a new cargo-audit release with updated dependencies

### ISSUE THREAD

**Issue by dotdash** [rustsec/rustsec#429]
cargo-audit 0.15.0 currently can't be installed using Rust < 1.51 without using `--locked` because it picks up a too recent version of `zeroize` (see #424). And it also can't be installed using `--locked` with more recent versions of Rust, because then it uses the old `git2` dependency from the lockfile which triggers a regression in rustc: https://github.com/rust-lang/rust/issues/85574

Therefore, I'd like to ask for a new release of cargo-audit that comes with the updated `Cargo.toml` file to restrict `zeroize` to <1.4 (already in master), and an updated `Cargo.lock` to use a more recent version of `git2`.

**Comment by marmeladema** [comment]
I am facing the same issue, I cannot install cargo-audit with rust 1.55.0 due to git2 dependency being too old.

**Comment by tarcieri** [comment]
cargo-audit v0.15.1 was released in #430

**Comment by marmeladema** [comment]
Thank you very much 🥰
