### ISSUE TITLE
cargo audit fails if CARGO_HOME doesn't exist

### ISSUE THREAD

**Issue by richardwhiuk** [rustsec/rustsec#45]
If `$CARGO_HOME` doesn't exist, `cargo audit` fails with:

```
> cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
error: couldn't fetch advisory database: bad parameter: not a directory: /builds/.cargo
```

It'd be good if `cargo-audit` handled this case.

**Comment by tarcieri** [comment]
This was fixed in https://github.com/RustSec/rustsec-crate/pull/43 but it has not yet been released

**Comment by richardwhiuk** [comment]
No it doesn't. That solves the problem if `$CARGO_HOME` is unset, not if the directory it points to doesn't exist.
