### ISSUE TITLE
cargo-audit unconditionally uses color escape codes when `--color=auto`

### ISSUE THREAD

**Issue by tmfink** [rustsec/rustsec#503]
`cargo-audit` always uses ANSI color escape codes, even when `--color=auto`.

## Actual Behavior 

```
$ cargo r audit --color=auto | file -
...
/dev/stdin: UTF-8 Unicode text, with escape sequences

$ cargo r audit | file -
...
/dev/stdin: UTF-8 Unicode text, with escape sequences
```

It seems that the `NO_COLOR` environment variable *is* respected:
```
$ NO_COLOR=1 cargo r audit | file -
...
/dev/stdin: UTF-8 Unicode text
```

## Desired Behavior

When `--color=auto`, ANSI escape codes should only be used when writing directly to a console (not when output redirected to a file or piped to another program).

**Comment by tarcieri** [comment]
Bumping to `clap` v4 will get rid of the `atty` dependency and replace it with `is-terminal`

**Comment by qtfkwk** [comment]
https://github.com/rustsec/rustsec/pull/1057
