### ISSUE TITLE
`platforms`: deal with platform removal

### ISSUE THREAD

**Issue by Shnatsel** [rustsec/rustsec#529]
Rust has recently dropped support for hermitkernel target, which caused the relevant entry to be removed from the `platfroms` crate as well (see #528). This is a **semver-breaking** change for `platforms` crate, because we currently have each platform as its own `pub const` entry.

We need to figure out some way to deal with platforms supported by Rust being removed without it being a breaking change every time.

**Comment by tarcieri** [comment]
Deprecation attributes seem like a reasonable enough way to deal with this?

**Comment by Shnatsel** [comment]
And/or a `discontinued: true` field.  Problem is, this prevents us from adding any new fields to the `Platform` struct in the future - in a somewhat roundabout way.

When generating a new version, we need to obtain the data about discontinued platforms *somehow,* but since they're no longer listed in the files we use as a source of this data, we can't do that directly. We could save the data about discontinued platforms ourselves somewhere in this repo, but that means we only save a select number of fields, and *that* means that we either cannot add any more fields to the `Platform` struct, or have to add a special "unknown" variant to every new field or wrap every new field in `Option`.

I think it would be easier to really remove discontinued platforms, drop the `pub const` and only provide an API that returns `Option<Platform>` given a target triple.

**Comment by tarcieri** [comment]
That sounds good to me

**Comment by Shnatsel** [comment]
I'll go ahead and implement it then :+1:

**Comment by Shnatsel** [comment]
Fixed by #531
