### ISSUE TITLE
cargo-audit does not check optional dependencies included by features

### ISSUE THREAD

**Issue by rajivshah3** [rustsec/rustsec#543]
We have a package that includes various dependencies if certain features are enabled. So, with the default features, we have a dependency tree that looks like this:

```
our-package
    - dep1
    - dep2
```

But if we want to enable a feature that includes additional dependencies, our dependency tree looks like this:

```
our-package
    - dep1
    - dep2
    - dep3
    - dep4
```

If a vulnerability arises in `dep3` or `dep4`, `cargo-audit` does not seem to report it

**Comment by tarcieri** [comment]
cargo-audit only looks at Cargo.lock.

Cargo.lock includes the complete dependency resolution for your project, regardless of what features are activated.

This sounds like something wrong with your environment. If you think otherwise, can you provide an example project which reproduces the issue?

**Comment by rajivshah3** [comment]
Ooh, you're right, that's my mistake 😅  I was running into an issue with https://github.com/iotaledger/crypto.rs. We have a `ed25519` feature which brings in `ed25519-zebra`. I was expecting `cargo audit` to report an issue with `rand_core` 0.5.1 (via `ed25519-zebra` -> `curve25519-dalek` -> rand_core`) since we got an alert about it in the Security tab on GitHub (it seems like they recently introduced Dependabot scanning for Rust). It turns out the alert from GitHub is incorrect. After looking at the RustSec advisory, it seems like only versions 0.6.0 and 0.6.1 `rand_core` are affected. GitHub is triggering an alert for all versions <0.6.2, when it should only be triggering for versions >=0.6.0 and <0.6.2.

Sorry about that!
