### ISSUE TITLE
Create new rustsec release with updated dependencies

### ISSUE THREAD

**Issue by mattsheerin** [rustsec/rustsec#567]
I'm currently failing to compile a Rust project because its dependency on rustsec is pulling in git2 0.13, but another dependency needs git2 0.14. I see that this has been bumped in main but there hasn't been a new release in 6 months. Can I please get a new release of rustsec so I can get the dependency updates?

**Comment by tarcieri** [comment]
We're aware. A new release will be out soon. It's just a lot of work.
