### ISSUE TITLE
`cargo audit` doesn't work well with `sparse-registry`

### ISSUE THREAD

**Issue by Xuanwo** [rustsec/rustsec#604]
[Databend](https://github.com/datafuselabs/databend) start a PR https://github.com/datafuselabs/databend/pull/6437 in insponse to [Call for testing: Cargo sparse-registry](https://internals.rust-lang.org/t/call-for-testing-cargo-sparse-registry/16862).

During this test, we found `cargo audit` doesn't work well with `sparse-registry`:

I expect to see this index updated within few seconds, however:

Before PR (18s):

https://github.com/datafuselabs/databend/runs/7169319361?check_suite_focus=true#step:3:1457

```shell
Sun, 03 Jul 2022 14:35:06 GMT Run cargo audit --db ./target/advisory-db
Sun, 03 Jul 2022 14:35:06 GMT Fetching advisory database from `[https://github.com/RustSec/advisory-db.git`](https://github.com/RustSec/advisory-db.git%60)
Sun, 03 Jul 2022 14:35:07 GMT Loaded 419 security advisories (from ./target/advisory-db)
Sun, 03 Jul 2022 14:35:07 GMT Updating crates.io index
Sun, 03 Jul 2022 14:35:25 GMT Scanning Cargo.lock for vulnerabilities (691 crate dependencies)
```

Within PR (sparse-registry disabled) (19s):

https://github.com/datafuselabs/databend/runs/7181217966?check_suite_focus=true#step:3:1462

```shell
Mon, 04 Jul 2022 13:27:26 GMT Run cargo audit --db ./target/advisory-db
Mon, 04 Jul 2022 13:27:26 GMT Fetching advisory database from `[https://github.com/RustSec/advisory-db.git`](https://github.com/RustSec/advisory-db.git%60)
Mon, 04 Jul 2022 13:27:27 GMT Loaded 419 security advisories (from ./target/advisory-db)
Mon, 04 Jul 2022 13:27:27 GMT Updating crates.io index
Mon, 04 Jul 2022 13:27:46 GMT Scanning Cargo.lock for vulnerabilities (693 crate dependencies)
```

Within PR (sparse-registry enabled) (18s):

https://github.com/datafuselabs/databend/runs/7181884244?check_suite_focus=true#step:3:1462

```shell
Mon, 04 Jul 2022 14:09:57 GMT Run cargo -Z sparse-registry audit --db ./target/advisory-db
Mon, 04 Jul 2022 14:09:57 GMT Fetching advisory database from `[https://github.com/RustSec/advisory-db.git`](https://github.com/RustSec/advisory-db.git%60)
Mon, 04 Jul 2022 14:09:58 GMT Loaded 419 security advisories (from ./target/advisory-db)
Mon, 04 Jul 2022 14:09:58 GMT Updating crates.io index
Mon, 04 Jul 2022 14:10:16 GMT Scanning Cargo.lock for vulnerabilities (693 crate dependencies)
```

**Comment by bjorn3** [comment]
When using `cargo -Zsparse-registry audit`, cargo doesn't pass through `-Zsparse-registry` to `cargo-audit`. You will have to enable it in `.cargo/config.toml` I think.

**Comment by tarcieri** [comment]
We don’t support arbitrary `-Z` flags you can pass to cargo, nor do we plan to. These are by definition unstable features.

Regarding access to the crates.io index, we use the `crates-index` crate, which is the place where support for the sparse index needs to be added.
