### ISSUE TITLE
Stop requiring the latest git commit in advisory-db to be signed

### ISSUE THREAD

**Issue by Shnatsel** [rustsec/rustsec#629]
We currently require the presence of _some_ signature on the latest commit in advisory-db repo for `cargo audit` and other tooling that uses `rustsec` crate to work.

This is completely useless in that it doesn't add any security. And it has broken production users twice now (both times for just a few minutes before it was noticed and fixed, but still).

We should disable that check.

**Comment by sidunder** [comment]
I'll have a go at creating a PR for this.
