### ISSUE TITLE
Add a search field on rustsec.org

### ISSUE THREAD

**Issue by amousset** [rustsec/rustsec#637]
As explained in https://github.com/rustsec/advisory-db/issues/1253 it is currently difficult to find an advisory marthing a specific CVE id (or some other details).

A way to address this in a general manner would be to add a search feature on rustsec.org. There are two main options:

* The easiest one is to use an third-party service (like [Algolia Docsearch](https://docsearch.algolia.com/) which is free for open-source projects), which can provide indexing and search results of good quality.
* The other option is to build a static index along with the site and to use a library like [lunr.js](https://lunrjs.com) to make the search.

**Comment by amousset** [comment]
Would using Algolia Docsearch be acceptable? It has some privacy drawbacks (as search queries are sent to a third-party) but I don't think it is worse than github in this regard.

**Comment by tarcieri** [comment]
Something which doesn't require a service integration (or if it does, doesn't require it to be tied to any particular person's user account) would be preferable, IMO

**Comment by amousset** [comment]
Ok, I'll see what I can do with static indexes.

**Comment by amousset** [comment]
Looks like we're even able to do it all in Rust https://github.com/tinysearch/tinysearch!

**Comment by amousset** [comment]
I have working prototypes with [stork](https://github.com/amousset/rustsec/tree/stork-search) and [lunr](https://github.com/amousset/rustsec/tree/lunr-search), the main problem is to get search on ids (CVE, etc.) to work, as hyphens are considered word separators so such queries do not give the expected result.

I have a partial workaround for lunr, and asked if something similar would be possible with stork (which seems to be the best option in all other aspects).

**Comment by tarcieri** [comment]
@amousset do they offer some sort of secondary index support?

**Comment by amousset** [comment]
Not that I'm aware of, client-side engines are quite limited. We could instead build a custom index and search, only over exact ids (`RUSTSEC-*`, `CVE-*`, etc.). This is trivial and would match the expressed need. 

It could also intercept the searches before the real search engine if we want it (but I'm wondering if it would be really useful, as including the full description produces indexes of a few megabytes, which is too much, so it would only search on metadata).
