### ISSUE TITLE
advisory-db: `crates/` directory sharding

### ISSUE THREAD

**Issue by pinkforest** [rustsec/rustsec#652]
I am slightly wondering about the `crates/` directory size as to amount of files - or directories directly under it.

In terms of the directory not being sharded e.g. how it is done in [crates.io-index](https://github.com/rust-lang/crates.io-index) repo.

As from the early dark ages of FTP servers I learned to shard them cos early legacy file systems

I am not sure if / whether it is a problem for anything including downstream users

It may be more of a problem if we end up merging all kinds of stuff e.g. a lot of unmaintained stuff especially

Close if we don't need to address this now / in future.

It would be nice to do some testing unless someone already has figured this out.

**Comment by tarcieri** [comment]
There are currently 442 advisories in the database, spread across 338 directories.

I don't think this is so many as to pose a practical problem. For comparison crates.io indexes 90,000 crates.

**Comment by pinkforest** [comment]
Yeah correct - probably not, I'll close this.

**Comment by tarcieri** [comment]
I looked into some rules of thumb for this. It seems like 10,000 entries is generally when people start splitting up directories by prefix (which seems to go back to ext2 having performance problems at that number)

**Comment by pinkforest** [comment]
yeah 10k I used to hold the limit, that was back in Solaris days and yeah ext2 :rofl:
