### ISSUE TITLE
crates.io login warning

### ISSUE THREAD

**Issue by dgjustice** [rustsec/rustsec#659]
I haven't been able to find any info on this, and it may be a n00b user error instead of a package issue.  I have tried this with and without `cargo login`, setting the registry env token, and even deleting the local cache.  I always get this warning.  I do not have a custom `~/.cargo/config`.

```console
cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 444 security advisories (from /home/user/.cargo/advisory-db)
    Updating crates.io index
warning: couldn't update crates.io index: registry: failed to acquire username/password from local configuration
    Scanning Cargo.lock for vulnerabilities (126 crate dependencies)
```

**Comment by tarcieri** [comment]
@dgjustice what was the solution here?

**Comment by dgjustice** [comment]
I have this in my gitconfig
```ini
[url "ssh://git@github.com/"]
  insteadOf = https://github.com/
```
I commented it out, and the warning went away.  FWIW, I haven't seen this error before with any other `cargo` command.  I closed the issue because I'm not sure if it is my local environment or not, and I don't want to send anyone chasing squirrels.  :smile:

**Comment by tarcieri** [comment]
Good to know, thanks!
