### ISSUE TITLE
Master doesn't exist in the advisory database

### ISSUE THREAD

**Issue by AwesomeIbex** [rustsec/rustsec#667]
Currently, cargo-audit tries to fetch from the master branch when it doesn't exist. Is there a command to workaround this?

```
    Replaced package `cargo-audit v0.17.0` with `cargo-audit v0.17.0 (https://github.com/rustsec/rustsec.git#2a080f17)` (executable `cargo-audit`)
..
cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
error: couldn't fetch advisory database: git operation failed: reference 'refs/heads/master' not found; class=Reference (4); code=NotFound (-3)
```

**Comment by amousset** [comment]
Can't reproduce:

```
> cargo install --git https://github.com/rustsec/rustsec.git#2a080f17 cargo-audit
[...]
    Replaced package `cargo-audit v0.17.0 (/home/amousset/projects/rustsec/cargo-audit)` with `cargo-audit v0.17.0 (https://github.com/rustsec/rustsec.git#2a080f17#2a080f17)` (executable `cargo-audit`)
> cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 447 security advisories (from /home/amousset/.cargo/advisory-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (269 crate dependencies)
```

The branch should have been renamed [since cargo-audit 0.15](https://github.com/rustsec/rustsec/commit/df400594abd6dc78ec4555042d1fa3c07a60c444).

**Comment by amousset** [comment]
Just to be sure, could you check:

* if you reproduce the problem with `cargo-audit audit`
* if so, what gives `cargo-audit --version`

**Comment by AwesomeIbex** [comment]
> Just to be sure, could you check:
> 
> * if you reproduce the problem with `cargo-audit audit`
> * if so, what gives `cargo-audit --version`

```
cargo-audit audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
error: couldn't fetch advisory database: git operation failed: reference 'refs/heads/master' not found; class=Reference (4); code=NotFound (-3)
```

```
cargo audit --version
cargo-audit-audit
```

**Comment by AwesomeIbex** [comment]
> 

From the logs, looks like you aren't fetching a fresh db? I don't have one already.

**Comment by amousset** [comment]
It's the same when removing the database:

```
> rm -fr /home/amousset/.cargo/advisory-db
> cargo-audit audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 447 security advisories (from /home/amousset/.cargo/advisory-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (4 crate dependencies)
```

And what does `cargo-audit --version` (with the -) give?

**Comment by tarcieri** [comment]
The `master` branch was used by old versions of `cargo-audit`.

Please upgrade to the latest version if you haven’t already.

**Comment by AwesomeIbex** [comment]
> Replaced package `cargo-audit v0.17.0` with `cargo-audit v0.17.0 (https://github.com/rustsec/rustsec.git#2a080f17)` (executable `cargo-audit`)

as you can see from the initial issue comment, `    Replaced package `cargo-audit v0.17.0` with `cargo-audit v0.17.0 (https://github.com/rustsec/rustsec.git#2a080f17)` (executable `cargo-audit`)
`

**Comment by tarcieri** [comment]
@AwesomeIbex have you tried `rm -rf ~/.cargo/advisory-db`?

**Comment by AwesomeIbex** [comment]
> @AwesomeIbex have you tried `rm -rf ~/.cargo/advisory-db`?

wowee! this worked. Weird.

**Comment by tarcieri** [comment]
Seems it had the old branch configured, although I thought we had logic in place to update it

**Comment by tarcieri** [comment]
Perhaps you still had a `.git` in there?
