### ISSUE TITLE
Present our .md in rustsec.org

### ISSUE THREAD

**Issue by pinkforest** [rustsec/rustsec#669]
Following from: https://github.com/rustsec/rustsec/pull/666

Would it be feasible / possible to link / embed / etc. howto unmaintained and contributing.md etc. from there to how to get started with contributing to advisories 

I mean those .md files in our advisory repo could be somehow presented in the website perhaps to foster new contribs thinking

**Comment by amousset** [comment]
This is easy to do, the website code already has a clone of the advisory-db repo and a markdown library.

**Comment by amousset** [comment]
![image](https://user-images.githubusercontent.com/329388/187544387-7a25bf2c-ce9c-4867-9ab7-11a3ea213b52.png)
done!

**Comment by amousset** [comment]
we'll just have to modify the source a bit to replace references to "this repository".

**Comment by tarcieri** [comment]
You could also modify the upstream document to use a wording that works for both (possibly a link)

**Comment by pinkforest** [comment]
Could be also nice to include some examples of various advisories e.g. "what looks good" or just plain templates as people don't seem to figure much unmaintained category exists :)

**Comment by Shnatsel** [comment]
This is now live on rustsec.org
