### ISSUE TITLE
Rust version-dependant UB in std functions in context of crates

### ISSUE THREAD

**Issue by pinkforest** [rustsec/rustsec#676]
Thinking of `mem::unitialized` - thanks @saethlin
https://github.com/rustsec/advisory-db/discussions/1195

What if we could consume advisories from under rust/std and make some sense out of them programmatically ?

I mean it's got the CVE ones but if we add RUSTSEC e.g. `informational "ub"` new type of advisories

Now this becomes controversial to flag e.g. say std env stuff but it _could be_ usable for `mem::unitialized`

But then difficulty becomes that environment visible rustc might not be same that does the build.

Also it still needs contextually affected crate(s) for the advisory as it is pointless to flag advisory on sole std func without any user.

Maybe if we add a flag `--include-rust` that could interrogate rustup show or rustc from path or smth ?

Or maybe cargo audit could be extended to binaries that were compiled with cargo-auditable (https://github.com/rust-secure-code/cargo-auditable/issues/50) and also understands the `.rustc` or new `.comment `section: https://github.com/rust-lang/rust/pull/97550

**Comment by saethlin** [comment]
I don't understand at all what you are suggesting here. Why does `rustup show` matter?

**Comment by pinkforest** [comment]
Because std function comes from the current rust version and we cannot flag `informational = "unsound"` on anything that is in std.

That said this would require call graph or related analysis between audited crate against used std and probably not something `cargo audit` should be scoped on

If we could flags unsound on some std functions from past versions that could warn somehow if they are used somewhere via advisory about the soundness of the whole thing.

But I guess this should exist somewhere else if it needs to exist...

**Comment by pinkforest** [comment]
e.g. let's say a crate yyy via crate xxx uses std `mem::unitialized` in incorrect manner - leading to UB - and we wonder if we should file advisory on crate xxx in relation where the std function is considered "unsound" until rust version z.z.z.

Problem here is that cargo audit etc. tooling doesn't know what rust version user is intending to build the crate on so advisory that is std-function and rust-version-dependant would be unusable unless the tooling knows whether rust version < z.z.z was used.

Bigger problem here also is that the crate yyy or crate xxx maintainer(s) tells us that they dont really "want" that advisory and they (strongly!) disagree it's a security issue and where we have not identified current downstream impact to refer to and other people in turn agree that it is some type of security issue.

How would you both avoid controversy and still signal to ecosystem in some useful way that something using that std function under certain rust versions via crates xxx/yyy might not be safe where actionable fix to that hypothetical issue would be simply to bump up the dependency that uses something else.

In addition how would you avoid getting users confused about highly technical advisories so that they don't generate the noise when they can just simply bump a dep and call it a day - all this without burning the maintainer in the process.

Normally we would use notice filed under the crate but it would require maintainer buy-in (in form of agreeing it's a vuln) making it often controversial since we cannot file unsound under crate as it doesn't meet it's criteria since the "soudness" issue is in std.

So we can't just flag std as whole currently but we would have to flag the std in relation with the crate(s) which in turn gets difficult because the crate xxx and/or crate yyy maintainer(s) told us that whatever was out there isn't a vuln (until proven if proven)

**Comment by pinkforest** [comment]
I'm just going to close this, I will need to write this up properly later and I'm too tired.
