### ISSUE TITLE
Website is using the `date` field for sorting

### ISSUE THREAD

**Issue by pinkforest** [rustsec/rustsec#685]
Date field can be backdated and the advisories appear out-of-order in https://rustsec.org/advisories/

Didn't the website have access to the repository and it could just look at the id-assigned commit date(s) until we get new fields to denote when it was published / updated ?

Yeah I know it requires index / caching and we can update those fields based on that later but before that ? :woman_shrugging: 

Simplest perhaps is probably first order by year and then order by serial on year instead of using date to sort ?

And then to generate index advisory -> date published from commit log for the website use

**Comment by brson** [comment]
Sorting the website listing by ID would be more intuitive to me. When I collect rustsec advisories for summarization I look at the order they are listed on the website, and I hadn't realize that some new ones were listed far down the page.

**Comment by amousset** [comment]
It has been deployed.
