### ISSUE TITLE
cargo-lock: Seralize lockfiles without explicit registries

### ISSUE THREAD

**Issue by UebelAndre** [rustsec/rustsec#687]
Recently an issue was reported to [rules_rust](https://github.com/bazelbuild/rules_rust) Bazel project related to how one of it's tools renders `Cargo.lock` files (https://github.com/bazelbuild/rules_rust/issues/1535#issue-1356876790). It seems the `cargo-lock` crate always renders registry entries into the lockfile when in some cases Cargo doesn't do this. It would be ideal to be able to serialize lockfiles to be byte for byte compatible with what Cargo would produce. Would it be possible or make sense to somehow control whether or not to render registry urls?

```diff
@@ -118,7 +118,7 @@ checksum = "7d6083ccb191711e9c2b80b22ee24a8381a18524444914c746d4239e21d1afaf"
 dependencies = [
  "askama_escape",
  "humansize",
- "nom 6.1.2",
+ "nom 6.1.2 (registry+https://github.com/rust-lang/crates.io-index)",
  "num-traits",
  "percent-encoding",
  "proc-macro2",
```

**Comment by tarcieri** [comment]
Can you post a complete reproduction of the issue?

That's the [`source`](https://docs.rs/cargo-lock/latest/cargo_lock/dependency/struct.Dependency.html#structfield.source) of a dependency, which should only be included if it's ambiguous, depending on the version of the lockfile.

**Comment by illicitonion** [comment]
In v3, I believe that Cargo's heuristic is "only include source if source is ambiguous", and it seems like cargo-lock's heuristic is "also include source if _version_ is ambiguous even if source isn't".

Here's a `Cargo.toml` and `Cargo.lock` generated by `cargo` which doesn't round-trip cleanly through `cargo-lock`:

Cargo.toml:
```toml
[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "=0.6.0"
bytestring = "=1.1.0"
```

Cargo.lock:
```toml
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3 

[[package]]
name = "bytes"
version = "0.6.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "e0dcbc35f504eb6fc275a6d20e4ebcda18cf50d40ba6fabff8c711fa16cb3b16"

[[package]]
name = "bytes"
version = "1.2.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "ec8a7b6a70fde80372154c65702f00a0f56f3e1c36abbc6c440484be248856db"

[[package]]
name = "bytestring"
version = "1.1.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "86b6a75fd3048808ef06af5cd79712be8111960adaf89d90250974b38fc3928a"
dependencies = [ 
 "bytes 1.2.1",
]

[[package]]
name = "example"
version = "0.1.0"
dependencies = [
 "bytes 0.6.0",
 "bytestring",
]
```

Small program which is a full repro:

```rust
use std::str::FromStr;

fn main() {
    let lockfile = r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3 

[[package]]
name = "bytes"
version = "0.6.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "e0dcbc35f504eb6fc275a6d20e4ebcda18cf50d40ba6fabff8c711fa16cb3b16"

[[package]]
name = "bytes"
version = "1.2.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "ec8a7b6a70fde80372154c65702f00a0f56f3e1c36abbc6c440484be248856db"

[[package]]
name = "bytestring"
version = "1.1.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "86b6a75fd3048808ef06af5cd79712be8111960adaf89d90250974b38fc3928a"
dependencies = [ 
 "bytes 1.2.1",
]

[[package]]
name = "example"
version = "0.1.0"
dependencies = [ 
 "bytes 0.6.0",
 "bytestring",
]
"#;
    println!("{}", cargo_lock::Lockfile::from_str(lockfile).unwrap().to_string());
}
```

**Comment by UebelAndre** [comment]
@tarcieri did the repro at https://github.com/rustsec/rustsec/issues/687#issuecomment-1243871492 reveal anything for you?

**Comment by tarcieri** [comment]
Sorry, I haven't had time to take a look yet

**Comment by UebelAndre** [comment]
> Sorry, I haven't had time to take a look yet

@tarcieri friendly ping 😅

**Comment by tarcieri** [comment]
I don’t have time to look at this right now.

Feel free to submit a PR.
