### ISSUE TITLE
Informational advisory fields

### ISSUE THREAD

**Issue by kornelski** [rustsec/rustsec#697]
The documentation doesn't clarify whether `Advisory.informational` being not-`None` means it's not a vulnerability and the other fields don't apply. If so, could this be in an `enum` that is mutually-exclusive with `cvss` field?

**Comment by pinkforest** [comment]
I already replied here: https://github.com/rustsec/rustsec/issues/698#issuecomment-1256939716

It's security vulnerability as others.
