### ISSUE TITLE
Rename or Deprecate `source` field

### ISSUE THREAD

**Issue by pinkforest** [rustsec/rustsec#712]
Coming up from: https://github.com/rustsec/rustsec/pull/682

We should just deprecate `source` since it's not used and our current policy is crates.io `registry` only.

Or even rename it -

Like will we ever flag advisories on some git repositories which may not even follow semver that we require ?

If we do then we should get a better name for that when we need it ?

And we shouldn't be hacking this with a loose string field ?

I don't think anyone should be required to parse Cargo.lock type of text strings either and make the required logic for that ?

Or in the case of curators the fields should be ergonomic to use - Cargo.lock isn't exactly ergonomic to use by hand ?

**Comment by tarcieri** [comment]
The main use case today is to allow others to use RustSec tooling to maintain internal vulnerability databases about internal package registries. As it were, I'm already using it in this capacity.

Beyond that, it would allow filing advisories in non-crates.io package repositories. While @RustSec may not do that ourselves, it might be useful for others.

Finally, knowing the source of the packages and advisories is crucial to properly auditing packages which come from multiple sources. Failure to properly track sources is the cause of innumerable issues and bugs which I have been working for a long time to squash (and that work still isn't complete).

See:
- #232
- #408
- #541
- #696

I think it's critically important for all parts of the overall system to be "source aware". A `package` name alone does not uniquely name a Rust package, but rather a 2-tuple of `(package_name, source)` does instead.
