### ISSUE TITLE
Advisories for `cargo audit` itself are printed for every scanned binary (instead of once)

### ISSUE THREAD

**Issue by Shnatsel** [rustsec/rustsec#736]
`cargo_audit::presenter::print_report` contains the following code:

https://github.com/rustsec/rustsec/blob/a7310a402b2809a88d62cdd770a6401fae2382ae/cargo-audit/src/presenter.rs#L166-L176

Since this function is run for every binary scanned, it will also print out the self-scan data for every single binary. This is unnecessarily noisy; this report should only be printed once, at the end.

**Comment by thewizzy** [comment]
@Shnatsel I gave this a go. 

I tried to disturb the execution paths as little as possible which mean breaking the the self report printing into a separate function.

**Comment by Shnatsel** [comment]
The approach sounds good to me. Please open a PR when you want someone to look over the code. You can open a draft PR if you want feedback before it's polished. Thanks!
