### ISSUE TITLE
Is it possible to include the CVSS scores from the NVD DB in the reports generated by cargo-audit?

### ISSUE THREAD

**Issue by asnaseer-resilient** [rustsec/rustsec#739]
We have been asked to ensure have no crates that have any CVSS score of 7 or more. Is there an easy way to use cargo-audit such that it also gives us these CVSS scores in its reports?

**Comment by tarcieri** [comment]
If you set `advisories.severity_threshold = "high"` in your audit.toml, it will only show advisories with a CVSS score of 7 or more, following the Qualitative Severity Rating Scale.

**Comment by asnaseer-resilient** [comment]
Thank you - sorry for not reading the docs thoroughly

**Comment by tarcieri** [comment]
Not your fault. It could be better documented.

**Comment by asnaseer-resilient** [comment]
@tarcieri Quick question - is there any setting that will include the actual severity (i.e. "none", "low", "medium", "high", "critical") in the output as well?
