### ISSUE TITLE
`cargo audit` >= 0.17.0 does not report yanked crates

### ISSUE THREAD

**Issue by roypat** [rustsec/rustsec#747]
Hello, 

It seems that started with version 0.17.0, the usage of yanked crates is no longer reported by `cargo audit`. Version 0.16.0 still correctly reports them. 

To reproduce, checkout the [firecracker](https://github.com/firecracker-microvm/firecracker) repo and run `cargo audit`. Version 0.16.0 will note that firecracker has a transitive dependency on the yanked `cpufeatures@0.2.1`, whereas version 0.17.0 and newer will not report any warnings.

**Comment by Shnatsel** [comment]
Thanks for the report!

I confirm I can reproduce this on a minimal example: 71a47aa21f7ccd7a0093bc07bd8a079bca0deadf

**Comment by Shnatsel** [comment]
The fix should ship in 0.17.4 in a few days. I've also added tests to make sure it doesn't regress again.

Thanks again for the report!

**Comment by roypat** [comment]
Thank you so much for the quick fix!

**Comment by Shnatsel** [comment]
v0.17.4 with this fix has shipped.
