### ISSUE TITLE
Get rid of OpenSSL

### ISSUE THREAD

**Issue by Shnatsel** [rustsec/rustsec#750]
`cargo audit` currently depends on OpenSSL:

```
cargo tree --all-features -i openssl-sys
openssl-sys v0.9.77
├── git2 v0.14.2
│   ├── cargo-edit v0.9.1
│   │   └── rustsec v0.26.3 (/home/shnatsel/Code/rustsec/rustsec)
│   │       └── cargo-audit v0.17.3 (/home/shnatsel/Code/rustsec/cargo-audit)
│   ├── crates-index v0.18.10
│   │   ├── cargo-edit v0.9.1 (*)
│   │   └── rustsec v0.26.3 (/home/shnatsel/Code/rustsec/rustsec) (*)
│   └── rustsec v0.26.3 (/home/shnatsel/Code/rustsec/rustsec) (*)
├── libgit2-sys v0.13.2+1.4.2
│   └── git2 v0.14.2 (*)
├── libssh2-sys v0.2.23
│   └── libgit2-sys v0.13.2+1.4.2 (*)
├── native-tls v0.2.10
│   └── ureq v2.5.0
│       └── cargo-edit v0.9.1 (*)
└── openssl v0.10.42
    └── native-tls v0.2.10 (*)
```

It's ironic to depend on a large source of CVEs in a tool that looks for CVEs.

#923 and #925 made progress in transitioning from `libgit2` to `gix`, and it is now gone in most configurations. There are some users of `libgit2` still remaining:

- [ ] `rustsec-admin` crate uses it via `crates-index`, needs to be converted to `tame-index`.
- [ ] `cargo-edit-9` uses `crates-index` and `libgit2` directly. This is used only when the `fix` feature is enabled. We should rewrite it outright, see https://github.com/rustsec/rustsec/issues/938

**Comment by tarcieri** [comment]
I would suggest removing the `git` dependency entirely and going the `ureq` route. There's so much environmental for errata that has lead to a litany of tiny issues for people.

The database tarball located at:

https://github.com/rustsec/advisory-db/archive/main.tar.gz

...is ~150kB, so we can just download and unpack that to do updates, caching etags or what not to determine if an update is needed.

**Comment by Shnatsel** [comment]
https://github.com/henry40408/git2-hyper provides a `hyper`-based transport for `libgit2` and exposes `rustls` as an option.

**Comment by Byron** [comment]
With the latest release of `crates-index`, this should be possible now. There is [some documentation](https://docs.rs/crates-index/2.0.0/crates_index/#using-rustls-instead-of-openssl-when-using-the-git-https-feature-in-applications) specifically about this topic in case you want to upgrade to v2.0 and give it a try.

**Comment by riking** [comment]
close issue? https://github.com/rustsec/rustsec/issues/939#issuecomment-1844414561

**Comment by Shnatsel** [comment]
https://github.com/rustsec/rustsec/pull/1121 dropped the last dependency chain that could lead to OpenSSL. So closing as completed :tada:
