### ISSUE TITLE
actions-rs is unmaintained

### ISSUE THREAD

**Issue by Finomnis** [rustsec/rustsec#773]
To integrate `cargo audit` into github actions, you officially recommend [`actions-rs/audit-check`](https://github.com/actions-rs/audit-check).

Sadly, the entire `actions-rs` suite seems to be unmaintained since 2020. This is not a problem in general, but right now github will soon stop supporting Node12 based actions and recommends all actions to be update to Node16. As this won't happen for `audit-check`, it will soon seize to work.

I'm not sure how to deal with this problem, I hoped to raise awareness here.

**Comment by tarcieri** [comment]
We have an open issue discussing this here: https://github.com/rustsec/audit-check/issues/2
