### ISSUE TITLE
Exported OSV advisories do not populate the top-level severity field

### ISSUE THREAD

**Issue by alpire** [rustsec/rustsec#781]
OSV 1.2.0 added a top-level [severity field](https://ossf.github.io/osv-schema/#severity-field), allowing to specify a CVSS as severity. RustSec currently export the CVSS under [affected[].database_specific](https://ossf.github.io/osv-schema/#affecteddatabase_specific-field): https://github.com/rustsec/rustsec/blob/2ea0ddc18551da0e906ae385dd60fc0d18ec8404/rustsec/src/osv/advisory.rs#L179

Would RustSec be open to also include the CVSS in the top-level severity field in the OSV advisories, when available? If so, I'd be happy to send a PR.

**Comment by tarcieri** [comment]
Sounds good to me

**Comment by Shnatsel** [comment]
Reopening because the PR was merged into master but the change is not reflected in the exported data yet.

**Comment by amousset** [comment]
It has been deployed since.
