### ISSUE TITLE
Fetching the crates.io index is slow

### ISSUE THREAD

**Issue by fenollp** [rustsec/rustsec#790]
I am seeing it being stuck on this last line:
```
λ cargo audit --ignore RUSTSEC-2020-0071
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 480 security advisories (from /home/pete/.cargo/advisory-db)
    Updating crates.io index
```

**Comment by tarcieri** [comment]
That seems like an issue with the `crates-index` crate

**Comment by Shnatsel** [comment]
This is an issue that Cargo itself also faces. The root if it is in `libgit2`'s inefficient delta resolution algorithm, combined with the large size of crates.io repository.

This will be fixed by migrating to `gitoxide` which is planned as part of #750
