### ISSUE TITLE
Lacking regular crates.io releases

### ISSUE THREAD

**Issue by kornelski** [rustsec/rustsec#807]
The last release of rustsec on crates.io is from November last year, and it has now-outdated dependencies. This causes duplicate crates in projects depending on rustsec.

Could you release rustsec crate more often?

**Comment by tarcieri** [comment]
As you've probably discovered in #808 we're dealing with some rather unfortunate dependency problems surrounding `cargo-edit` and `git2`. It sure would be nice if the upgrade was that easy, but it isn't.

You might want to look through the PRs and issues on this, namely #801. We can't easily upgrade `cargo-edit` without removing the `--fix` functionality as the relevant functionality in `cargo-edit` has been removed and it can no longer be used for our purposes.

We will likely need to vendor the relevant functionality into the `rustsec` crate, which I've been meaning to do but have been busy with other things.

**Comment by tarcieri** [comment]
The real blocker here is #801, so I'm going to close this.

**Comment by Shnatsel** [comment]
Thanks to @pinkforest the next release is unblocked, so I published v0.26.5 just now. If you encounter any more issues with outdated dependencies, please let us know.
