### ISSUE TITLE
Incorrect report when your local package name matches that of a crate in the audit database

### ISSUE THREAD

**Issue by thebracket** [rustsec/rustsec#821]
I included `cargo audit` in a class I was teaching, and was amused to discover that because I had a local package in the class workspace called `scratchpad` - I was using it as a live-coding example - when I ran `cargo audit` it gave me a vulnerability for `scratchpad`. I hadn't imported the crate from the crates repo.

Not a big deal, but probably something to consider for the future.

**Comment by tarcieri** [comment]
A reproduction for this issue would be helpful.

We do consider the `source` of a package when selecting vulnerabilities, but it's possible there's a bug in that logic.

See also: #232

**Comment by thebracket** [comment]
Here's the simplest reproduction I can come up with:

```
cargo new scratchpad
cd scratchpad
cargo audit
```

Yields:
```
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 514 security advisories (from C:\Users\Herbert\.cargo\advisory-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (1 crate dependencies)
Crate:     scratchpad
Version:   0.1.0
Title:     move_elements can double-free objects on panic
Date:      2021-02-18
ID:        RUSTSEC-2021-0030
URL:       https://rustsec.org/advisories/RUSTSEC-2021-0030
Solution:  Upgrade to >=1.3.1
Dependency tree:
scratchpad 0.1.0

error: 1 vulnerability found!
```

This is pretty clearly incorrect. `Cargo.toml` and `src/main.rs` are both the defaults generate by cargo:

```toml
[package]
name = "scratchpad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

```

And main.rs:

```rust
fn main() {
    println!("Hello, world!");
}

```

`Cargo.lock`, since I have no dependencies, is pretty bare:

```
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "scratchpad"
version = "0.1.0"
```

**Comment by Shnatsel** [comment]
Looks like a duplicate of #696 to me
