### ISSUE TITLE
CI: cargo audit tests take a long time

### ISSUE THREAD

**Issue by pinkforest** [rustsec/rustsec#832]
test auditable_binary_with_vulnerabilities_fails has been running for over 60 seconds
test auditable_binary_without_vulnerabilities_passes has been running for over 60 second

~13+ minutes on all platforms:

Windows: https://github.com/rustsec/rustsec/actions/runs/4467658995/jobs/7847399841?pr=831#step:6:282
MacOS: https://github.com/rustsec/rustsec/actions/runs/4467658995/jobs/7847397875#step:6:279

Some GitHub red herring or something we may need to cache somewhere perhaps ?

EDIT: Doesn't seem to be red herring - 2nd run doing the same on all platforms each over 10 mins:

https://github.com/rustsec/rustsec/actions/runs/4467898232/jobs/7847945238?pr=831

**Comment by Shnatsel** [comment]
Just using the default DB location should help, actually.

**Comment by Shnatsel** [comment]
Actually it's much simpler than that: the caching seems to be broken.

https://github.com/rustsec/rustsec/actions/runs/4485191049/jobs/7886488822?pr=835#step:12:2

**Comment by Shnatsel** [comment]
#839 shaves 5 minutes off the CI time, but caching is still broken.

**Comment by tarcieri** [comment]
Might be worth updating #551 and see if the issues have resolved themselves in the interim

**Comment by Shnatsel** [comment]
We've gotten CI times under control. They are 1-2 minutes now. Closing.
