### ISSUE TITLE
advisory-db: CI linter Takes 1m 30 sec each PR

### ISSUE THREAD

**Issue by pinkforest** [rustsec/rustsec#846]
Every PR in advisory-db the linter takes 1m 30s each time.

https://github.com/rustsec/advisory-db/actions/runs/4519170146/jobs/7959502197#step:5:1

I had a mild thought (I should have known better) that it might have been the 500+ log lines it spits out but that's not the case.

The runner just runs it slowly.

Would it be in PR's feasible to reduce the linter to the files that were touched as part of the PR ?

On push it could still stay as all files - or even have a periodic run sans every push instead.

**Comment by tarcieri** [comment]
It's slow because it's communicating with the crates.io API.

That said, I don't think 1m30s is a terribly long time?

**Comment by pinkforest** [comment]
ah ofcourse - so that's the crates-index which transparently pulls the index - didn't we have this cached now ?

e.g. didn't we fix this caching issue in:
https://github.com/rustsec/rustsec/issues/832

And could use the same cachign in advisory-db

**Comment by tarcieri** [comment]
It's communicating directly with the crates.io API.

Perhaps that communication can be replaced with `crates-index`.

**Comment by pinkforest** [comment]
The linter doesn't seem to communicate with the API - it's already using the database via crates-index ?
https://github.com/rustsec/rustsec/blob/main/admin/src/linter.rs#L155

**Comment by tarcieri** [comment]
Aah, never mind, guess that already happened.

Then I'm not sure why it's so slow.

**Comment by pinkforest** [comment]
No caching. Should be easy to copy caching from here to there me thinks.

**Comment by pinkforest** [comment]
Looks like we need to use [Index::with_path](https://docs.rs/crates-index/latest/crates_index/struct.Index.html#method.with_path) and put the index repo into cache - I'll see if crates-index could get rid of git2 dependency in case of local path.

**Comment by Shnatsel** [comment]
I think putting the index into the CI cache should be sufficient. Incremental updates to it should be pretty quick.

Regarding getting rid of `git2`, the upstream is interested in migrating to `gitoxide` and @BlackHoleFox is working on a PR.

**Comment by pinkforest** [comment]
Yeah true simple incremental works - the crates.io-index gets re-rolled every three months due to sheer size of the history and needs to handle the pull in a way that it doesn't break it.
