### ISSUE TITLE
cargo-audit/0.17.5 release was not completed

### ISSUE THREAD

**Issue by chenrui333** [rustsec/rustsec#847]
👋 it looks like there is [a release PR](https://github.com/rustsec/rustsec/pull/840), but [the release flow](https://github.com/rustsec/rustsec/actions/workflows/release.yml) did not get triggered somehow. Raise some issue in here for some awareness, thanks!

**Comment by tarcieri** [comment]
I think the issue is there's a `v` missing from the version number... the tag should be `cargo-audit/v0.17.5`.

Will retag.

**Comment by chenrui333** [comment]
Yeah, I think re-tag sounds about right, but it would be better to just skip the problematic release.

**Comment by tarcieri** [comment]
Retagging it triggered the release build: https://github.com/rustsec/rustsec/actions/runs/4520317487

**Comment by tarcieri** [comment]
>  it would be better to just skip the problematic release (if not much hassle).

It's just a problem with the tag, nothing more

**Comment by chenrui333** [comment]
okay, thanks @tarcieri!

**Comment by chenrui333** [comment]
that was quick! 👍
