### ISSUE TITLE
How to scan non-Rust projects?

### ISSUE THREAD

**Issue by mcandre** [rustsec/rustsec#861]
Okay that sounds dumb so let me explain.

I enjoy using Rust CLI tools in non-Rust projects. For example, using ripgrep for assorted build tasks in a Python project.

I can obtain ripgrep via cargo install, but cargo audit does not appear to scan tools for CVE's, that are provisioned this way. cargo audit only scans runtime dependencies tracked in a cargo lockfile.

What's more, cargo rejects Cargo.toml files that lack a version field. Well, I don't want to write a version field in a Cargo.toml project for non-Rust projects. I already version my non-Rust projects elsewhere, so that would violate DRY. Furthermore, the Cargo.toml file is rejected if it lacks a lib or bin Rust source file. Well, again, non-Rust projects don't have Rust source files to satisfy that cargo requirement.

By contrast, the Python SAC tool `safety` is able to scan for CVE's on tools installed via pip.

Could there be a way for cargo audit to include scanning arbitrary `cargo install <tool>`'s?

Perhaps it's time to introduce a hook into cargo install that automatically exits non-zero and emits stderr warnings about any known CVE's. Similar to NPM and RubyGems.

Perhaps it's time for crates.io to even yank package versions with known CVE's.

**Comment by Shnatsel** [comment]
`cargo audit bin` already does this, try e.g. `cargo audit bin $(which ripgrep)`. 

But it's limited in what it can detect if the Rust CLI programs weren't installed with [`cargo auditable`](https://github.com/rust-secure-code/cargo-auditable). So ideally you'd run

```bash
cargo auditable install ripgrep
cargo audit bin $(which ripgrep)
```

You can also run `cargo audit bin ~/.cargo/bin/*` to audit all binaries installed via Cargo.
