### ISSUE TITLE
cargo audit: automatically generate missing lockfiles

### ISSUE THREAD

**Issue by mcandre** [rustsec/rustsec#863]
Problem:

Rust developers who maintain library-only crates, are advised not to commit lockfiles to version control.

The developers are likely to remain unaware of their CVE's, until some other downstream developer creates a binary using their library, and knows to use cargo audit, and makes the effort to inform upstream maintainers.

A malicious developer may deliberately avoid informing the mainainers.

Mitigation:

Proactively generate a cargo lockfile during `cargo audit`, whenever one is missing.

**Comment by tarcieri** [comment]
Closing due to lack of a response
