### ISSUE TITLE
Respect `[registries.crates-io] protocol = "sparse"` set in cargo config

### ISSUE THREAD

**Issue by Logarithmus** [rustsec/rustsec#866]
I have this in my global cargo config:
```toml
[registries.crates-io]
protocol = "sparse"
```

Would like `cargo audit` to respect it instead of forcibly downloading the slow git index. From the code I can see you already support sparse registries, but only if they are specified in `Cargo.lock`. But as you can see [here](https://blog.rust-lang.org/2022/06/22/sparse-registry-testing.html#:~:text=Cargo.lock%20files%20will%20continue%20to%20reference%20the%20existing%20crates.io%20index%20on%20GitHub%20to%20avoid%20churn..), "Cargo.lock files will continue to reference the existing crates.io index on GitHub to avoid churn". So your current approach doesn't work.

**Comment by tarcieri** [comment]
We use the `crates-index` crate to fetch the index: https://github.com/frewsxcv/rust-crates-index

Please see the tracking issue there: https://github.com/frewsxcv/rust-crates-index/issues/87

**Comment by Logarithmus** [comment]
@tarcieri they added sparse registry support, but only for local cache, it can't fetch anything from the network. So I guess this is still blocked.
