### ISSUE TITLE
`cargo audit` fails because of an outdated branch name

### ISSUE THREAD

**Issue by signed-log** [rustsec/rustsec#881]
Running `cargo audit` on Rust nightly :

```
rustc 1.71.0-nightly (a77c55248 2023-05-06) (from rustc 1.71.0-nightly (39c6804b9 2023-04-19)) (nightly-x86_64-unknown-linux-gnu)
```

Leads to

```
Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
error: couldn't fetch advisory database: git operation failed: reference 'refs/h
eads/master' not found; class=Reference (4); code=NotFound (-3)
```

Looking at the repo, `master` doesn't exist anymore and `main` is the new branch

**Comment by tarcieri** [comment]
How long ago did you clone https://github.com/RustSec/advisory-db.git?

The branch name was changed over 2 years ago.

There's supposed to be code to update the branch name, but regardless, I would suggest just deleting the local copy of the repo and checking out a clean one.

**Comment by signed-log** [comment]
> There's supposed to be code to update the branch name, but regardless, I would suggest just deleting the local copy of the repo and checking out a clean one.

This is what I ended up doing

> How long ago did you clone https://github.com/RustSec/advisory-db.git?

A few days ago, but I think my network connection dropped in the middle of the clone which made it angry, thanks !
