### ISSUE TITLE
Make website search field case-insensitive

### ISSUE THREAD

**Issue by faern** [rustsec/rustsec#913]
Searching for `Foobar` shows no results even if there are advisories for the crate `foobar`. I see no reason for this search to be case-sensitive?

This is a more noticeable problem on mobile, where words are auto-capitalized. It lead to me not finding any advisory on crate that had two (https://github.com/Gilnaa/memoffset/issues/76).

**Comment by Shnatsel** [comment]
Ah, that sounds like an oversight. Thank you for reporting! Should be just a matter of adding `.toLowerCase()` to the search string.

**Comment by amousset** [comment]
Indeed, search should be case insensitive.

**Comment by amousset** [comment]
The fix is now published.

**Comment by faern** [comment]
Thank you for the swift response!
