### ISSUE TITLE
Redesign `cargo audit fix`

### ISSUE THREAD

**Issue by Shnatsel** [rustsec/rustsec#938]
`cargo audit fix` has been disabled by default for a very long time, and its current architecture relying on a fork of `cargo-edit` is infeasible to maintain. Its `Cargo.toml` editing also arguably should not be the default; it's the `Cargo.lock` that should be changed first and foremost.

We need to switch the implementation to calling `cargo update` or, once that's stabilized, `cargo upgrade`.

The minimum viable product is a tool that calls `cargo update --package` with the list of vulnerable packages.

A wishlist for the more complete solution looks something like this:

- `--minimal-versions` to update to the first fixed version instead of the latest available version
  -  Whether this should be the default is an open question
- `--breaking` flag to allow breaking changes when they are required to fix a vulnerability

We can re-add TOML editing later backed by `cargo upgrade`, with something like `--toml` flag. This should default to requiring the minimum fixed version, so an implementation of `--minimal-versions` is also a prerequisite. It should also support `--breaking`.

**Comment by tarcieri** [comment]
Something somewhat tricky any implementation that invokes `cargo update` will likely have to deal with is qualifying the vulnerable package to be upgraded with its version, e.g. `cargo update --package package@vulnerable_version`, which is needed in the event there are multiple versions of the same dependency package in a Cargo project

**Comment by Shnatsel** [comment]
An initial redesign and rewrite has landed in  #1113
