### ISSUE TITLE
Cargo audit incorrectly flags serde_cbor when a package is specified

### ISSUE THREAD

**Issue by Firstyear** [rustsec/rustsec#946]
Hi there,

As part of webauthn-rs we forked serde-cbor into serde-cbor-2 to maintain it. We were using this:

```
serde_cbor = { version = "0.12.0-dev", package = "serde_cbor_2" }
```

Some users have reported that cargo-audit still flags this as being the unmainted serde-cbor as I suspect that cargo-audit may not be examining the package statement. Is this something that can be improved?

**Comment by Shnatsel** [comment]
Thanks for reporting the issue!

Could you point us to a repository where it can be reproduced? We need at least the `Cargo.lock` file.

**Comment by Firstyear** [comment]
On webauthn-rs https://github.com/kanidm/webauthn-rs/tree/d4b418487ff7726464549b43bf850509694c3e74 at this commit or prior. We internally just renamed everything to serde_cbor_2 to resolve and avoid this for now.

**Comment by Shnatsel** [comment]
That's not a false positive. The project really does still depend on `serde_cbor` in one place:

```
$ cargo tree -i serde_cbor
serde_cbor v0.11.2
└── authenticator-ctap2-2021 v0.3.2-dev.1
    └── authenticator-cli v0.1.0 (/home/shnatsel/Code/webauthn-rs/authenticator-cli)
```

**Comment by Firstyear** [comment]
Sorry for the noise :(

**Comment by Shnatsel** [comment]
No worries. We'd rather have people over-report issues than under-report them :wink:

**Comment by Firstyear** [comment]
> No worries. We'd rather have people over-report issues than under-report them 😉

Yeah, I was proxy-reporting this from a trusted community member and didn't vet the issue myself. Thanks as always for the work on cargo audit and rust security in general. You're doing wonderful things. ❤️
